#!/bin/bash

# Generated by Claude Sonnet 4
# GPU Check Script for Container Runtime
# This script checks if GPU support is available in the container environment

set -euo pipefail

# Function to log with timestamp
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

# Function to check for NVIDIA GPU support
check_nvidia_gpu() {
    log "Checking for NVIDIA GPU support..."
    
    # Check if nvidia-smi is available
    if command -v nvidia-smi >/dev/null 2>&1; then
        log "nvidia-smi found, attempting to query GPU"
        if nvidia-smi >/dev/null 2>&1; then
            log "NVIDIA GPU detected via nvidia-smi"
            return 0
        else
            log "nvidia-smi present but failed to query GPU"
        fi
    else
        log "nvidia-smi not found"
    fi
    
    # Check for NVIDIA device files
    if [ -c /dev/nvidia0 ] || [ -c /dev/nvidiactl ] || [ -c /dev/nvidia-uvm ]; then
        log "NVIDIA device files detected in /dev"
        return 0
    fi
    
    # Check for NVIDIA in lspci output
    if command -v lspci >/dev/null 2>&1; then
        if lspci 2>/dev/null | grep -i nvidia >/dev/null 2>&1; then
            log "NVIDIA GPU detected via lspci"
            return 0
        fi
    fi
    
    return 1
}

# Function to check for AMD GPU support
check_amd_gpu() {
    log "Checking for AMD GPU support..."
    
    # Check for AMD device files
    if [ -c /dev/dri/card0 ] || [ -c /dev/dri/renderD128 ]; then
        log "AMD/DRI device files detected in /dev/dri"
        return 0
    fi
    
    # Check for AMD in lspci output
    if command -v lspci >/dev/null 2>&1; then
        if lspci 2>/dev/null | grep -i amd >/dev/null 2>&1; then
            log "AMD GPU detected via lspci"
            return 0
        fi
    fi
    
    return 1
}

# Function to check for Intel GPU support
check_intel_gpu() {
    log "Checking for Intel GPU support..."
    
    # Check for Intel device files
    if [ -c /dev/dri/card0 ] || [ -c /dev/dri/renderD128 ]; then
        log "Intel/DRI device files detected in /dev/dri"
        # Additional check for Intel specifically
        if command -v lspci >/dev/null 2>&1; then
            if lspci 2>/dev/null | grep -i intel | grep -i vga >/dev/null 2>&1; then
                log "Intel GPU detected via lspci"
                return 0
            fi
        fi
    fi
    
    return 1
}

# Function to check container runtime GPU environment variables
check_runtime_env() {
    log "Checking container runtime GPU environment..."
    
    # Check for common GPU environment variables
    if [ -n "${NVIDIA_VISIBLE_DEVICES:-}" ]; then
        log "NVIDIA_VISIBLE_DEVICES set: $NVIDIA_VISIBLE_DEVICES"
        return 0
    fi
    
    if [ -n "${CUDA_VISIBLE_DEVICES:-}" ]; then
        log "CUDA_VISIBLE_DEVICES set: $CUDA_VISIBLE_DEVICES"
        return 0
    fi
    
    if [ -n "${ROCR_VISIBLE_DEVICES:-}" ]; then
        log "ROCR_VISIBLE_DEVICES set: $ROCR_VISIBLE_DEVICES"
        return 0
    fi
    
    return 1
}

# Function to check for Apple Silicon GPU support
check_apple_gpu() {
    log "Checking for Apple Silicon GPU support..."
    
    # Check for Apple Silicon specific indicators
    if [ "$(uname -m)" = "aarch64" ] || [ "$(uname -m)" = "arm64" ]; then
        log "ARM64 architecture detected"
        
        # Check for Metal framework indicators (macOS specific)
        if [ -n "${METAL_DEVICE_WRAPPER_TYPE:-}" ]; then
            log "Metal GPU framework detected"
            return 0
        fi
        
        # Check for Apple GPU in device tree or similar
        if [ -d /sys/class/drm ] && ls /sys/class/drm/card* >/dev/null 2>&1; then
            log "DRM graphics devices detected on ARM64"
            return 0
        fi
        
        # Check for ARM Mali or Apple GPU in lspci/lshw if available
        if command -v lshw >/dev/null 2>&1; then
            if lshw -C display 2>/dev/null | grep -i "apple\|mali\|arm" >/dev/null 2>&1; then
                log "ARM/Apple GPU detected via lshw"
                return 0
            fi
        fi
    fi
    
    return 1
}

# Function to check for general GPU indicators
check_general_gpu() {
    log "Checking for general GPU indicators..."
    
    # Check /proc/driver/nvidia if it exists
    if [ -d /proc/driver/nvidia ]; then
        log "NVIDIA driver proc directory found"
        return 0
    fi
    
    # Check for GPU-related mount points
    if mount | grep -q gpu; then
        log "GPU-related mount points detected"
        return 0
    fi
    
    # Check for hardware info if lshw is available
    if command -v lshw >/dev/null 2>&1; then
        if lshw -C display 2>/dev/null | grep -i "3d\|gpu\|graphics\|nvidia\|amd\|intel" >/dev/null 2>&1; then
            log "GPU detected via lshw hardware scan"
            return 0
        fi
    fi
    
    return 1
}

# Main execution
main() {
    log "Starting GPU check in container environment"
    log "Container runtime: ${CONTAINER_RUNTIME:-unknown}"
    log "Hostname: $(hostname)"
    
    # Initialize GPU support flag
    gpu_support=false
    
    # Run all GPU checks
    if check_runtime_env; then
        gpu_support=true
    fi
    
    if check_nvidia_gpu; then
        gpu_support=true
    fi
    
    if check_amd_gpu; then
        gpu_support=true
    fi
    
    if check_intel_gpu; then
        gpu_support=true
    fi
    
    if check_apple_gpu; then
        gpu_support=true
    fi
    
    if check_general_gpu; then
        gpu_support=true
    fi
    
    # Output result in a format that the Go code can parse
    if [ "$gpu_support" = true ]; then
        log "GPU support detected"
        echo "GPU_CHECK_SUCCESS"
        echo "GPU Support: Yes"
        exit 0
    else
        log "No GPU support detected"
        echo "GPU_CHECK_FAILED"
        echo "GPU Support: No"
        exit 0
    fi
}

# Execute main function
main "$@"