#!/bin/bash

# Generated by Claude Sonnet 4
# Apple Silicon GPU Check Script
# This script checks specifically for Apple Silicon GPU support

set -euo pipefail

# Function to log with timestamp
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

# Function to check for Apple Silicon GPU support
check_apple_gpu() {
    log "Checking for Apple Silicon GPU support..."
    
    # Check for Metal framework indicators (macOS specific)
    if [ -n "${METAL_DEVICE_WRAPPER_TYPE:-}" ]; then
        log "Metal GPU framework detected"
        return 0
    fi
    
    # Check specifically for Apple GPU in lspci/lshw
    if command -v lshw >/dev/null 2>&1; then
        if lshw -C display 2>/dev/null | grep -i "apple" >/dev/null 2>&1; then
            log "Apple GPU detected via lshw"
            return 0
        fi
    fi
    
    # Check for DRI devices (libkrun virtualized GPU) with Apple-specific validation
    if [ -c /dev/dri/card0 ] || [ -c /dev/dri/renderD128 ]; then
        # Only consider DRI devices valid for Apple Silicon if we can confirm it's Apple
        if [ "$(uname -s)" = "Darwin" ] || [ -n "${METAL_DEVICE_WRAPPER_TYPE:-}" ]; then
            log "Apple Silicon/DRI device files detected in /dev/dri"
            return 0
        fi
    fi
    
    # Check for Vulkan support with Apple-specific context
    if command -v vulkaninfo >/dev/null 2>&1; then
        # Only consider Vulkan valid if we're in a Darwin context or have Metal indicators
        if [ "$(uname -s)" = "Darwin" ] || [ -n "${METAL_DEVICE_WRAPPER_TYPE:-}" ]; then
            if vulkaninfo >/dev/null 2>&1; then
                log "Vulkan support detected in Apple context"
                return 0
            fi
        fi
    fi
    
    return 1
}

# Main execution
main() {
    log "Starting Apple Silicon GPU check in container environment"
    log "Container runtime: ${CONTAINER_RUNTIME:-unknown}"
    log "Hostname: $(hostname 2>/dev/null || echo 'unknown')"
    log "Architecture: $(uname -m)"
    
    if check_apple_gpu; then
        log "Apple Silicon GPU detected"
        echo "GPU_TYPE=APPLE"
        echo "GPU_CHECK_SUCCESS"
        echo "GPU Support: Yes"
        exit 0
    else
        log "No Apple Silicon GPU detected"
        echo "GPU_TYPE=NONE"
        echo "GPU_CHECK_FAILED"
        echo "GPU Support: No"
        exit 0
    fi
}

# Execute main function
main "$@"