#!/bin/bash

# Generated by Claude Sonnet 4
# NVIDIA GPU Check Script
# This script checks specifically for NVIDIA GPU support

set -euo pipefail

# Function to log with timestamp
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

# Function to check for NVIDIA GPU support
check_nvidia_gpu() {
    log "Checking for NVIDIA GPU support..."
    
    # Check if nvidia-smi is available
    if command -v nvidia-smi >/dev/null 2>&1; then
        log "nvidia-smi found, attempting to query GPU"
        if nvidia-smi >/dev/null 2>&1; then
            log "NVIDIA GPU detected via nvidia-smi"
            return 0
        else
            log "nvidia-smi present but failed to query GPU"
        fi
    else
        log "nvidia-smi not found"
    fi
    
    # Check for NVIDIA device files
    if [ -c /dev/nvidia0 ] || [ -c /dev/nvidiactl ] || [ -c /dev/nvidia-uvm ]; then
        log "NVIDIA device files detected in /dev"
        return 0
    fi
    
    # Check for NVIDIA in lspci output
    if command -v lspci >/dev/null 2>&1; then
        if lspci 2>/dev/null | grep -i nvidia >/dev/null 2>&1; then
            log "NVIDIA GPU detected via lspci"
            return 0
        fi
    fi
    
    # Check for NVIDIA environment variables
    if [ -n "${NVIDIA_VISIBLE_DEVICES:-}" ]; then
        log "NVIDIA_VISIBLE_DEVICES set: $NVIDIA_VISIBLE_DEVICES"
        return 0
    fi
    
    if [ -n "${CUDA_VISIBLE_DEVICES:-}" ]; then
        log "CUDA_VISIBLE_DEVICES set: $CUDA_VISIBLE_DEVICES"
        return 0
    fi
    
    return 1
}

# Main execution
main() {
    log "Starting NVIDIA GPU check in container environment"
    log "Container runtime: ${CONTAINER_RUNTIME:-unknown}"
    log "Hostname: $(hostname 2>/dev/null || echo 'unknown')"
    
    if check_nvidia_gpu; then
        log "NVIDIA GPU detected"
        echo "GPU_TYPE=NVIDIA"
        echo "GPU_CHECK_SUCCESS"
        echo "GPU Support: Yes"
        exit 0
    else
        log "No NVIDIA GPU detected"
        echo "GPU_TYPE=NONE"
        echo "GPU_CHECK_FAILED"
        echo "GPU Support: No"
        exit 0
    fi
}

# Execute main function
main "$@"