#!/bin/bash

# Generated by Claude Sonnet 4
# Apple Silicon GPU Check Script
# This script checks specifically for Apple Silicon GPU support

set -euo pipefail

# Function to log with timestamp
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

# Function to check for Apple Silicon GPU support
check_apple_gpu() {
    log "Checking for Apple Silicon GPU support..."
    
    # Check for Apple Silicon specific indicators
    if [ "$(uname -m)" = "aarch64" ] || [ "$(uname -m)" = "arm64" ]; then
        log "ARM64 architecture detected"
        
        # Check for Metal framework indicators (macOS specific)
        if [ -n "${METAL_DEVICE_WRAPPER_TYPE:-}" ]; then
            log "Metal GPU framework detected"
            return 0
        fi
        
        # Check for Apple GPU in device tree or similar
        if [ -d /sys/class/drm ] && ls /sys/class/drm/card* >/dev/null 2>&1; then
            log "DRM graphics devices detected on ARM64"
            return 0
        fi
        
        # Check for DRI devices (libkrun virtualized GPU)
        if [ -c /dev/dri/card0 ] || [ -c /dev/dri/renderD128 ]; then
            log "Apple Silicon/DRI device files detected in /dev/dri"
            return 0
        fi
        
        # Check for ARM Mali or Apple GPU in lspci/lshw if available
        if command -v lshw >/dev/null 2>&1; then
            if lshw -C display 2>/dev/null | grep -i "apple\|mali\|arm" >/dev/null 2>&1; then
                log "ARM/Apple GPU detected via lshw"
                return 0
            fi
        fi
        
        # Check for Vulkan support (key for llama.cpp)
        if command -v vulkaninfo >/dev/null 2>&1; then
            if vulkaninfo >/dev/null 2>&1; then
                log "Vulkan support detected on Apple Silicon"
                return 0
            fi
        fi
        
        # For libkrun environments, we assume GPU is available if we're on ARM64
        log "ARM64 detected - assuming Apple Silicon GPU available"
        return 0
    fi
    
    return 1
}

# Main execution
main() {
    log "Starting Apple Silicon GPU check in container environment"
    log "Container runtime: ${CONTAINER_RUNTIME:-unknown}"
    log "Hostname: $(hostname 2>/dev/null || echo 'unknown')"
    log "Architecture: $(uname -m)"
    
    if check_apple_gpu; then
        log "Apple Silicon GPU detected"
        echo "GPU_TYPE=APPLE"
        echo "GPU_CHECK_SUCCESS"
        echo "GPU Support: Yes"
        exit 0
    else
        log "No Apple Silicon GPU detected"
        echo "GPU_TYPE=NONE"
        echo "GPU_CHECK_FAILED"
        echo "GPU Support: No"
        exit 0
    fi
}

# Execute main function
main "$@"