#!/bin/bash

# Generated by Claude Sonnet 4
# Intel GPU Check Script
# This script checks specifically for Intel GPU support

set -euo pipefail

# Function to log with timestamp
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

# Function to check for Intel GPU support
check_intel_gpu() {
    log "Checking for Intel GPU support..."
    
    # Check for Intel device files
    if [ -c /dev/dri/card0 ] || [ -c /dev/dri/renderD128 ]; then
        log "Intel/DRI device files detected in /dev/dri"
        # Additional check for Intel specifically
        if command -v lspci >/dev/null 2>&1; then
            if lspci 2>/dev/null | grep -i intel | grep -i "vga\|display\|3d" >/dev/null 2>&1; then
                log "Intel GPU detected via lspci"
                return 0
            fi
        fi
    fi
    
    # Check for Intel in lspci output
    if command -v lspci >/dev/null 2>&1; then
        if lspci 2>/dev/null | grep -i intel | grep -i "vga\|display\|3d\|graphics" >/dev/null 2>&1; then
            log "Intel GPU detected via lspci"
            return 0
        fi
    fi
    
    # Check for Intel GPU tools
    if command -v intel_gpu_top >/dev/null 2>&1; then
        log "intel_gpu_top found - Intel GPU tools available"
        return 0
    fi
    
    # Check for Intel GPU environment variables
    if [ -n "${INTEL_DEVICE:-}" ]; then
        log "INTEL_DEVICE set: $INTEL_DEVICE"
        return 0
    fi
    
    return 1
}

# Main execution
main() {
    log "Starting Intel GPU check in container environment"
    log "Container runtime: ${CONTAINER_RUNTIME:-unknown}"
    log "Hostname: $(hostname 2>/dev/null || echo 'unknown')"
    
    if check_intel_gpu; then
        log "Intel GPU detected"
        echo "GPU_TYPE=INTEL"
        echo "GPU_CHECK_SUCCESS"
        echo "GPU Support: Yes"
        exit 0
    else
        log "No Intel GPU detected"
        echo "GPU_TYPE=NONE"
        echo "GPU_CHECK_FAILED"
        echo "GPU Support: No"
        exit 0
    fi
}

# Execute main function
main "$@"