#!/bin/bash

# Generated by Claude Sonnet 4
# Apple Silicon GPU Check Script
# This script checks specifically for Apple Silicon GPU support

set -euo pipefail

# Function to log with timestamp
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

# Function to check for Apple Silicon GPU support
check_apple_gpu() {
    log "Checking for Apple Silicon GPU support..."
    
    # Check for DRI devices (the real indicator for Apple Silicon GPU in containers)
    if [ -c /dev/dri/card0 ] || [ -c /dev/dri/renderD128 ]; then
        log "Apple Silicon/DRI device files detected in /dev/dri"
        return 0
    fi
    
    # Check for Metal framework indicators (macOS specific)
    if [ -n "${METAL_DEVICE_WRAPPER_TYPE:-}" ]; then
        log "Metal GPU framework detected"
        return 0
    fi
    
    log "No Apple Silicon GPU indicators found"
    return 1
}

# Main execution
main() {
    log "Starting Apple Silicon GPU check in container environment"
    log "Container runtime: ${CONTAINER_RUNTIME:-unknown}"
    log "Hostname: $(hostname 2>/dev/null || echo 'unknown')"
    log "Architecture: $(uname -m)"
    
    if check_apple_gpu; then
        log "Apple Silicon GPU detected"
        echo "GPU_TYPE=APPLE"
        echo "GPU_CHECK_SUCCESS"
        echo "GPU Support: Yes"
        exit 0
    else
        log "No Apple Silicon GPU detected"
        echo "GPU_TYPE=NONE"
        echo "GPU_CHECK_FAILED"
        echo "GPU Support: No"
        exit 0
    fi
}

# Execute main function
main "$@"