#!/bin/bash

# Generated by Claude Sonnet 4
# AMD GPU Check Script
# This script checks specifically for AMD GPU support

set -euo pipefail

# Function to log with timestamp
log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $*"
}

# Function to check for AMD GPU support
check_amd_gpu() {
    log "Checking for AMD GPU support..."
    
    # Check for AMD device files
    if [ -c /dev/dri/card0 ] || [ -c /dev/dri/renderD128 ]; then
        log "AMD/DRI device files detected in /dev/dri"
        # Additional check for AMD specifically
        if command -v lspci >/dev/null 2>&1; then
            if lspci 2>/dev/null | grep -i amd >/dev/null 2>&1; then
                log "AMD GPU detected via lspci"
                return 0
            fi
        fi
    fi
    
    # Check for AMD in lspci output
    if command -v lspci >/dev/null 2>&1; then
        if lspci 2>/dev/null | grep -i amd | grep -i "vga\|display\|3d" >/dev/null 2>&1; then
            log "AMD GPU detected via lspci"
            return 0
        fi
    fi
    
    # Check for ROCm environment variables
    if [ -n "${ROCR_VISIBLE_DEVICES:-}" ]; then
        log "ROCR_VISIBLE_DEVICES set: $ROCR_VISIBLE_DEVICES"
        return 0
    fi
    
    # Check for ROCm installation
    if command -v rocm-smi >/dev/null 2>&1; then
        log "rocm-smi found, attempting to query GPU"
        if rocm-smi >/dev/null 2>&1; then
            log "AMD GPU detected via rocm-smi"
            return 0
        fi
    fi
    
    return 1
}

# Main execution
main() {
    log "Starting AMD GPU check in container environment"
    log "Container runtime: ${CONTAINER_RUNTIME:-unknown}"
    log "Hostname: $(hostname 2>/dev/null || echo 'unknown')"
    
    if check_amd_gpu; then
        log "AMD GPU detected"
        echo "GPU_TYPE=AMD"
        echo "GPU_CHECK_SUCCESS"
        echo "GPU Support: Yes"
        exit 0
    else
        log "No AMD GPU detected"
        echo "GPU_TYPE=NONE"
        echo "GPU_CHECK_FAILED"
        echo "GPU Support: No"
        exit 0
    fi
}

# Execute main function
main "$@"