#!/usr/bin/env python3
# Generated by Claude Code
# Documentation indexing script for krknctl Lightspeed RAG

import argparse
import os
import sys
import json
import logging
from typing import List, Dict, Any
from pathlib import Path

import requests
from bs4 import BeautifulSoup
import html2text
import numpy as np
from sentence_transformers import SentenceTransformer
import faiss

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class DocumentationIndexer:
    def __init__(self):
        self.model = SentenceTransformer('all-MiniLM-L6-v2')  # Lightweight embedding model
        self.documents = []
        self.embeddings = None
        self.index = None
        
    def scrape_krkn_docs(self) -> List[Dict[str, Any]]:
        """Scrape documentation from krkn-chaos.dev"""
        docs = []
        base_url = "https://krkn-chaos.dev"
        
        try:
            # Main documentation pages to scrape
            doc_paths = [
                "/",
                "/docs/",
                "/docs/installation/",
                "/docs/scenarios/",
                "/docs/scenarios/node_scenarios/",
                "/docs/scenarios/pod_scenarios/", 
                "/docs/scenarios/application_outages/",
                "/docs/scenarios/zone_outages/",
                "/docs/scenarios/litmus_scenarios/",
                "/docs/config/",
                "/docs/contribute/",
                "/docs/krknctl/",
            ]
            
            h = html2text.HTML2Text()
            h.ignore_links = False
            h.ignore_images = True
            
            for path in doc_paths:
                try:
                    url = f"{base_url}{path}"
                    logger.info(f"Scraping {url}")
                    
                    response = requests.get(url, timeout=30)
                    response.raise_for_status()
                    
                    soup = BeautifulSoup(response.content, 'html.parser')
                    
                    # Extract main content (adjust selector based on actual site structure)
                    content_selectors = [
                        'main', 'article', '.content', '.documentation', 
                        '[role="main"]', '#content', '.markdown-body'
                    ]
                    
                    content = None
                    for selector in content_selectors:
                        content_elem = soup.select_one(selector)
                        if content_elem:
                            content = h.handle(str(content_elem))
                            break
                    
                    if not content:
                        # Fallback: use body content
                        content = h.handle(str(soup.body)) if soup.body else ""
                    
                    if content.strip():
                        docs.append({
                            "url": url,
                            "title": soup.title.string if soup.title else path,
                            "content": content.strip(),
                            "source": "krkn-chaos.dev"
                        })
                        
                except Exception as e:
                    logger.warning(f"Failed to scrape {url}: {e}")
                    continue
                    
        except Exception as e:
            logger.error(f"Error scraping krkn documentation: {e}")
            
        return docs
    
    def load_krknctl_help(self) -> List[Dict[str, Any]]:
        """Load krknctl help content"""
        docs = []
        
        try:
            help_file = Path("/app/krknctl_help.txt")
            if help_file.exists():
                with open(help_file, 'r') as f:
                    content = f.read()
                    
                docs.append({
                    "url": "krknctl://help",
                    "title": "krknctl Help Documentation", 
                    "content": content,
                    "source": "krknctl"
                })
                    
        except Exception as e:
            logger.warning(f"Failed to load krknctl help: {e}")
            
        return docs
    
    def chunk_documents(self, docs: List[Dict[str, Any]], chunk_size: int = 512) -> List[Dict[str, Any]]:
        """Split documents into smaller chunks for better retrieval"""
        chunked_docs = []
        
        for doc in docs:
            content = doc["content"]
            words = content.split()
            
            # Split into chunks
            for i in range(0, len(words), chunk_size):
                chunk_words = words[i:i + chunk_size]
                chunk_content = " ".join(chunk_words)
                
                if len(chunk_content.strip()) > 50:  # Only keep meaningful chunks
                    chunked_docs.append({
                        "url": doc["url"],
                        "title": doc["title"],
                        "content": chunk_content,
                        "source": doc["source"],
                        "chunk_id": len(chunked_docs)
                    })
                    
        return chunked_docs
    
    def create_embeddings(self, docs: List[Dict[str, Any]]) -> np.ndarray:
        """Create embeddings for document chunks"""
        logger.info(f"Creating embeddings for {len(docs)} document chunks")
        
        texts = [doc["content"] for doc in docs]
        embeddings = self.model.encode(texts, show_progress_bar=True)
        
        return embeddings
    
    def build_faiss_index(self, embeddings: np.ndarray) -> faiss.Index:
        """Build FAISS index for similarity search"""
        dimension = embeddings.shape[1]
        index = faiss.IndexFlatIP(dimension)  # Inner product for cosine similarity
        
        # Normalize embeddings for cosine similarity
        faiss.normalize_L2(embeddings)
        index.add(embeddings)
        
        return index
    
    def save_index(self, docs: List[Dict[str, Any]], embeddings: np.ndarray, 
                   index: faiss.Index, output_dir: str):
        """Save the complete index to disk"""
        os.makedirs(output_dir, exist_ok=True)
        
        # Save FAISS index
        faiss.write_index(index, os.path.join(output_dir, "index.faiss"))
        
        # Save documents metadata
        with open(os.path.join(output_dir, "documents.json"), 'w') as f:
            json.dump(docs, f, indent=2)
            
        # Save embeddings
        np.save(os.path.join(output_dir, "embeddings.npy"), embeddings)
        
        logger.info(f"Index saved to {output_dir}")
        
    def build_index(self, live_mode: bool = True, output_dir: str = "/app/docs_index"):
        """Build the complete documentation index"""
        logger.info("Building documentation index...")
        
        # Collect documents
        all_docs = []
        
        # Load krknctl help (always available)
        all_docs.extend(self.load_krknctl_help())
        
        # Scrape live documentation if in live mode
        if live_mode:
            all_docs.extend(self.scrape_krkn_docs())
        else:
            logger.info("Skipping live documentation scraping (offline mode)")
            
        if not all_docs:
            raise Exception("No documents found to index")
            
        logger.info(f"Found {len(all_docs)} documents")
        
        # Chunk documents
        chunked_docs = self.chunk_documents(all_docs)
        logger.info(f"Created {len(chunked_docs)} document chunks")
        
        # Create embeddings
        embeddings = self.create_embeddings(chunked_docs)
        
        # Build FAISS index
        index = self.build_faiss_index(embeddings)
        
        # Save everything
        self.save_index(chunked_docs, embeddings, index, output_dir)
        
        logger.info("Documentation index built successfully!")

def main():
    parser = argparse.ArgumentParser(description="Build krknctl documentation index")
    parser.add_argument("--build-cached-index", action="store_true", 
                       help="Build cached index (for container build time)")
    parser.add_argument("--live-index", action="store_true",
                       help="Build live index with fresh documentation")
    
    args = parser.parse_args()
    
    indexer = DocumentationIndexer()
    
    try:
        if args.build_cached_index:
            # Build cached index (used during container build)
            indexer.build_index(live_mode=True, output_dir="/app/cached_docs")
        elif args.live_index:
            # Build live index (used at runtime)
            indexer.build_index(live_mode=True, output_dir="/app/docs_index")
        else:
            # Default: build live index
            indexer.build_index(live_mode=True, output_dir="/app/docs_index")
            
    except Exception as e:
        logger.error(f"Failed to build index: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()