#!/usr/bin/env python3
# Generated by Claude Code
# Documentation indexing script for krknctl Lightspeed RAG

import argparse
import os
import sys
import json
import logging
from typing import List, Dict, Any
from pathlib import Path

import requests
import base64
import numpy as np
from sentence_transformers import SentenceTransformer
import faiss

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class DocumentationIndexer:
    def __init__(self, home_dir: str = "/app"):
        self.model = SentenceTransformer('all-MiniLM-L6-v2')  # Lightweight embedding model
        self.documents = []
        self.embeddings = None
        self.index = None
        self.home_dir = home_dir
        
    def scrape_krkn_docs(self) -> List[Dict[str, Any]]:
        """Fetch documentation from GitHub repository using GitHub API"""
        docs = []
        github_api_base = "https://api.github.com/repos/krkn-chaos/website/contents"
        docs_path = "content/en/docs"
        
        try:
            # Recursively fetch all markdown files from the docs directory
            docs = self._fetch_github_docs_recursive(github_api_base, docs_path)
            logger.info(f"Found {len(docs)} documents from GitHub")
            
        except Exception as e:
            logger.error(f"Error during GitHub documentation fetching: {e}")
            
        return docs
    
    def _fetch_github_docs_recursive(self, api_base: str, path: str) -> List[Dict[str, Any]]:
        """Recursively fetch markdown files from GitHub repository"""
        docs = []
        
        try:
            # Get directory contents from GitHub API
            url = f"{api_base}/{path}"
            logger.info(f"Fetching from GitHub API: {url}")
            
            response = requests.get(url, timeout=30)
            response.raise_for_status()
            
            contents = response.json()
            
            for item in contents:
                if item['type'] == 'file' and item['name'].endswith('.md'):
                    # Fetch markdown file content
                    doc = self._fetch_github_file(item)
                    if doc:
                        docs.append(doc)
                        
                elif item['type'] == 'dir':
                    # Recursively process subdirectories
                    subdocs = self._fetch_github_docs_recursive(api_base, item['path'])
                    docs.extend(subdocs)
                    
        except requests.RequestException as e:
            logger.warning(f"Failed to fetch from GitHub API {path}: {e}")
            
        return docs
    
    def _fetch_github_file(self, file_info: Dict[str, Any]) -> Dict[str, Any]:
        """Fetch individual markdown file from GitHub"""
        try:
            # Get file content from GitHub API
            response = requests.get(file_info['download_url'], timeout=30)
            response.raise_for_status()
            
            content = response.text
            
            # Parse frontmatter if present
            title = file_info['name'].replace('.md', '').replace('_', ' ').title()
            
            # Try to extract title from frontmatter
            if content.startswith('---'):
                try:
                    parts = content.split('---', 2)
                    if len(parts) >= 3:
                        frontmatter = parts[1]
                        content_body = parts[2].strip()
                        
                        # Extract title from frontmatter
                        for line in frontmatter.split('\n'):
                            if line.strip().startswith('title:'):
                                title = line.split(':', 1)[1].strip().strip('"\'')
                                break
                        
                        content = content_body
                except:
                    # If frontmatter parsing fails, use original content
                    pass
            
            # Generate documentation URL
            github_url = f"https://github.com/krkn-chaos/website/blob/main/{file_info['path']}"
            docs_url = f"https://krkn-chaos.dev/docs/{file_info['path'].replace('content/en/docs/', '').replace('.md', '/')}"
            
            return {
                "url": docs_url,
                "title": title,
                "content": content,
                "source": "krkn-chaos/website",
                "github_url": github_url,
                "path": file_info['path']
            }
            
        except Exception as e:
            logger.warning(f"Failed to fetch file {file_info['name']}: {e}")
            return None
    
    def load_krknctl_help(self) -> List[Dict[str, Any]]:
        """Load krknctl help content"""
        docs = []
        
        try:
            help_file = Path(os.path.join(self.home_dir, "krknctl_help.txt"))
            if help_file.exists():
                with open(help_file, 'r') as f:
                    content = f.read()
                    
                docs.append({
                    "url": "krknctl://help",
                    "title": "krknctl Help Documentation", 
                    "content": content,
                    "source": "krknctl"
                })
                    
        except Exception as e:
            logger.warning(f"Failed to load krknctl help: {e}")
            
        return docs
    
    def chunk_documents(self, docs: List[Dict[str, Any]], chunk_size: int = 512) -> List[Dict[str, Any]]:
        """Split documents into smaller chunks for better retrieval"""
        chunked_docs = []
        
        for doc in docs:
            content = doc["content"]
            words = content.split()
            
            # Split into chunks
            for i in range(0, len(words), chunk_size):
                chunk_words = words[i:i + chunk_size]
                chunk_content = " ".join(chunk_words)
                
                if len(chunk_content.strip()) > 50:  # Only keep meaningful chunks
                    chunked_docs.append({
                        "url": doc["url"],
                        "title": doc["title"],
                        "content": chunk_content,
                        "source": doc["source"],
                        "chunk_id": len(chunked_docs)
                    })
                    
        return chunked_docs
    
    def create_embeddings(self, docs: List[Dict[str, Any]]) -> np.ndarray:
        """Create embeddings for document chunks"""
        logger.info(f"Creating embeddings for {len(docs)} document chunks")
        
        texts = [doc["content"] for doc in docs]
        embeddings = self.model.encode(texts, show_progress_bar=True)
        
        return embeddings
    
    def build_faiss_index(self, embeddings: np.ndarray) -> faiss.Index:
        """Build FAISS index for similarity search"""
        dimension = embeddings.shape[1]
        index = faiss.IndexFlatIP(dimension)  # Inner product for cosine similarity
        
        # Normalize embeddings for cosine similarity
        faiss.normalize_L2(embeddings)
        index.add(embeddings)
        
        return index
    
    def save_index(self, docs: List[Dict[str, Any]], embeddings: np.ndarray, 
                   index: faiss.Index, output_dir: str):
        """Save the complete index to disk"""
        os.makedirs(output_dir, exist_ok=True)
        
        # Save FAISS index
        faiss.write_index(index, os.path.join(output_dir, "index.faiss"))
        
        # Save documents metadata
        with open(os.path.join(output_dir, "documents.json"), 'w') as f:
            json.dump(docs, f, indent=2)
            
        # Save embeddings
        np.save(os.path.join(output_dir, "embeddings.npy"), embeddings)
        
        logger.info(f"Index saved to {output_dir}")
        
    def build_index(self, live_mode: bool = True, output_dir: str = None):
        """Build the complete documentation index"""
        if output_dir is None:
            output_dir = os.path.join(self.home_dir, "docs_index")
        logger.info(f"Building documentation index to {output_dir}...")
        
        # Collect documents
        all_docs = []
        
        # Load krknctl help (always available)
        all_docs.extend(self.load_krknctl_help())
        
        # Scrape live documentation if in live mode
        if live_mode:
            all_docs.extend(self.scrape_krkn_docs())
        else:
            logger.info("Skipping live documentation scraping (offline mode)")
            
        if not all_docs:
            raise Exception("No documents found to index")
            
        logger.info(f"Found {len(all_docs)} documents")
        
        # Chunk documents
        chunked_docs = self.chunk_documents(all_docs)
        logger.info(f"Created {len(chunked_docs)} document chunks")
        
        # Create embeddings
        embeddings = self.create_embeddings(chunked_docs)
        
        # Build FAISS index
        index = self.build_faiss_index(embeddings)
        
        # Save everything
        self.save_index(chunked_docs, embeddings, index, output_dir)
        
        logger.info("Documentation index built successfully!")

def main():
    parser = argparse.ArgumentParser(description="Build krknctl documentation index")
    parser.add_argument("--home", 
                        default="/app",
                        help="Base directory for RAG service files (default: /app for container, override for local testing)")
    parser.add_argument("--build-cached-index", action="store_true", 
                       help="Build cached index (for container build time)")
    parser.add_argument("--live-index", action="store_true",
                       help="Build live index with fresh documentation")
    parser.add_argument("--output-dir",
                       help="Output directory for the index (overrides default behavior)")
    
    args = parser.parse_args()
    
    # Ensure home directory exists
    os.makedirs(args.home, exist_ok=True)
    
    indexer = DocumentationIndexer(home_dir=args.home)
    
    try:
        if args.build_cached_index:
            # Build cached index (used during container build)
            output_dir = args.output_dir or os.path.join(args.home, "cached_docs")
            indexer.build_index(live_mode=True, output_dir=output_dir)
        elif args.live_index:
            # Build live index (used at runtime)
            output_dir = args.output_dir or os.path.join(args.home, "docs_index")
            indexer.build_index(live_mode=True, output_dir=output_dir)
        else:
            # Default: build live index
            output_dir = args.output_dir or os.path.join(args.home, "docs_index")
            indexer.build_index(live_mode=True, output_dir=output_dir)
            
    except Exception as e:
        logger.error(f"Failed to build index: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()