#!/usr/bin/env python3
# Generated by Claude Code
# FastAPI RAG service for krknctl Lightspeed

import argparse
import json
import logging
import os
from contextlib import asynccontextmanager
from typing import List, Dict, Any, Optional
from pathlib import Path

import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
import faiss
from sentence_transformers import SentenceTransformer
import ollama

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Global RAG service instance (will be initialized on startup)
rag_service = None

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Manage application lifespan (startup and shutdown)"""
    global rag_service
    
    # Startup
    logger.info("Starting RAG service...")
    try:
        # Initialize RAG service with default home directory
        rag_service = RAGService(home_dir="/app")
        rag_service.load_index()
        logger.info("RAG service initialized successfully")
    except Exception as e:
        logger.error(f"Failed to initialize RAG service: {e}")
        raise
    
    yield
    
    # Shutdown (cleanup if needed)
    logger.info("RAG service shutting down...")

app = FastAPI(title="krknctl Lightspeed RAG Service", version="1.0.0", lifespan=lifespan)

class QueryRequest(BaseModel):
    query: str
    max_results: int = 5
    stream: bool = False

class QueryResponse(BaseModel):
    response: str
    sources: List[Dict[str, Any]]
    query: str

class RAGService:
    def __init__(self, home_dir: str = "/app"):
        self.model = None
        self.index = None
        self.documents = []
        self.embeddings = None
        self.ollama_client = ollama.Client()
        self.home_dir = home_dir
        
    def load_index(self, index_dir: Optional[str] = None):
        """Load the pre-built documentation index"""
        if index_dir is None:
            index_dir = os.path.join(self.home_dir, "docs_index")
        
        # Ensure the index directory exists
        os.makedirs(index_dir, exist_ok=True)
        logger.info(f"Loading index from {index_dir}")
        
        try:
            # Load sentence transformer model
            self.model = SentenceTransformer('all-MiniLM-L6-v2')
            
            # Load FAISS index
            index_path = os.path.join(index_dir, "index.faiss")
            if not os.path.exists(index_path):
                raise FileNotFoundError(f"Index file not found: {index_path}")
            self.index = faiss.read_index(index_path)
            
            # Load documents metadata
            docs_path = os.path.join(index_dir, "documents.json")
            if not os.path.exists(docs_path):
                raise FileNotFoundError(f"Documents file not found: {docs_path}")
            with open(docs_path, 'r') as f:
                self.documents = json.load(f)
                
            # Load embeddings
            embeddings_path = os.path.join(index_dir, "embeddings.npy")
            if os.path.exists(embeddings_path):
                self.embeddings = np.load(embeddings_path)
                
            logger.info(f"Index loaded successfully: {len(self.documents)} documents")
            
        except Exception as e:
            logger.error(f"Failed to load index: {e}")
            raise
            
    def search_documents(self, query: str, max_results: int = 5) -> List[Dict[str, Any]]:
        """Search for relevant documents using semantic similarity"""
        if not self.model or not self.index:
            raise RuntimeError("Index not loaded")
            
        # Create query embedding
        query_embedding = self.model.encode([query])
        faiss.normalize_L2(query_embedding)
        
        # Search in FAISS index
        scores, indices = self.index.search(query_embedding, max_results)
        
        # Retrieve matching documents
        results = []
        for score, idx in zip(scores[0], indices[0]):
            if idx < len(self.documents):
                doc = self.documents[idx].copy()
                doc["relevance_score"] = float(score)
                results.append(doc)
                
        return results
    
    def generate_response(self, query: str, context_docs: List[Dict[str, Any]], 
                         stream: bool = False) -> str:
        """Generate response using Ollama with RAG context"""
        
        # Build context from retrieved documents
        context_parts = []
        for doc in context_docs:
            source = f"Source: {doc['source']} - {doc['title']}"
            content = doc['content'][:500]  # Limit context length
            context_parts.append(f"{source}\n{content}")
            
        context = "\n\n---\n\n".join(context_parts)
        
        # Create prompt for krknctl-specific assistance
        prompt = f"""You are a helpful assistant for krknctl, a chaos engineering tool. Based on the provided documentation context, answer the user's question about krknctl commands, scenarios, or chaos engineering practices.

Context from krknctl documentation:
{context}

User Question: {query}

Please provide a helpful answer using this format:
- Use emojis to make the response friendly (🚀 ⚙️ 💡 ⚠️ etc.)
- Provide a clear explanation of what the command does
- List relevant parameters with emojis
- End with the exact krknctl command in a box like this:

┌─────────────────────────────────────────┐
│ krknctl run scenario-name --flag=value │
└─────────────────────────────────────────┘

Keep your response concise and practical. Do not use markdown formatting, backticks, or **bold** text.

Answer:"""

        try:
            if stream:
                # Return streaming generator for real-time responses
                response = self.ollama_client.generate(
                    model='llama3.2:1b',
                    prompt=prompt,
                    stream=True
                )
                return response
            else:
                # Return complete response
                response = self.ollama_client.generate(
                    model='llama3.2:1b', 
                    prompt=prompt,
                    stream=False
                )
                return response['response']
                
        except Exception as e:
            logger.error(f"Error generating response: {e}")
            return f"I encountered an error while processing your request. Please try again or check if the Ollama service is running properly."


@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {
        "status": "healthy",
        "service": "krknctl-lightspeed-rag",
        "model": "llama3.2:1b",
        "documents_indexed": len(rag_service.documents) if rag_service.documents else 0
    }

@app.post("/query", response_model=QueryResponse)
async def query_rag(request: QueryRequest):
    """Query the RAG system for krknctl assistance"""
    try:
        if not rag_service.model or not rag_service.index:
            raise HTTPException(status_code=503, detail="RAG service not initialized")
            
        # Search for relevant documents
        relevant_docs = rag_service.search_documents(request.query, request.max_results)
        
        if not relevant_docs:
            raise HTTPException(status_code=404, detail="No relevant documentation found")
            
        # Generate response
        if request.stream:
            # Handle streaming separately
            raise HTTPException(status_code=400, detail="Use /query/stream for streaming responses")
            
        response_text = rag_service.generate_response(request.query, relevant_docs, stream=False)
        
        # Prepare sources for response
        sources = []
        for doc in relevant_docs:
            sources.append({
                "title": doc.get("title", ""),
                "url": doc.get("url", ""),
                "source": doc.get("source", ""),
                "relevance_score": doc.get("relevance_score", 0.0)
            })
            
        return QueryResponse(
            response=response_text,
            sources=sources,
            query=request.query
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error processing query: {e}")
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")

@app.post("/query/stream")
async def query_rag_stream(request: QueryRequest):
    """Query the RAG system with streaming response"""
    try:
        if not rag_service.model or not rag_service.index:
            raise HTTPException(status_code=503, detail="RAG service not initialized")
            
        # Search for relevant documents
        relevant_docs = rag_service.search_documents(request.query, request.max_results)
        
        if not relevant_docs:
            raise HTTPException(status_code=404, detail="No relevant documentation found")
            
        # Generate streaming response
        def generate_stream():
            try:
                response_stream = rag_service.generate_response(request.query, relevant_docs, stream=True)
                for chunk in response_stream:
                    if chunk.get('response'):
                        yield f"data: {json.dumps({'text': chunk['response']})}\n\n"
                        
                # Send sources at the end
                sources = []
                for doc in relevant_docs:
                    sources.append({
                        "title": doc.get("title", ""),
                        "url": doc.get("url", ""),
                        "source": doc.get("source", ""),
                        "relevance_score": doc.get("relevance_score", 0.0)
                    })
                yield f"data: {json.dumps({'sources': sources, 'query': request.query})}\n\n"
                yield "data: [DONE]\n\n"
                
            except Exception as e:
                yield f"data: {json.dumps({'error': str(e)})}\n\n"
                
        return StreamingResponse(
            generate_stream(),
            media_type="text/event-stream",
            headers={
                "Cache-Control": "no-cache",
                "Connection": "keep-alive",
            }
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error processing streaming query: {e}")
        raise HTTPException(status_code=500, detail=f"Internal server error: {str(e)}")

@app.get("/")
async def root():
    """Root endpoint with service information"""
    return {
        "service": "krknctl Lightspeed RAG",
        "version": "1.0.0",
        "description": "Retrieval-Augmented Generation service for krknctl chaos engineering assistance",
        "endpoints": {
            "health": "/health",
            "query": "/query",
            "stream": "/query/stream"
        }
    }

def parse_args():
    """Parse command line arguments"""
    parser = argparse.ArgumentParser(description='krknctl Lightspeed RAG Service')
    parser.add_argument('--home', 
                        default='/app',
                        help='Base directory for RAG service files (default: /app for container, override for local testing)')
    parser.add_argument('--host',
                        default='0.0.0.0',
                        help='Host to bind the service to (default: 0.0.0.0)')
    parser.add_argument('--port',
                        type=int,
                        default=8080,
                        help='Port to bind the service to (default: 8080)')
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()
    
    # Ensure home directory exists
    os.makedirs(args.home, exist_ok=True)
    
    # Initialize global RAG service with specified home directory
    rag_service = RAGService(home_dir=args.home)
    
    logger.info(f"Starting RAG service with home directory: {args.home}")
    
    import uvicorn
    uvicorn.run(app, host=args.host, port=args.port)