changelog:
  exclude:
    labels: ["ignore-for-release"]
  categories:
    - title: "🚀 Features"
      labels: ["feature", "enhancement"]
    - title: "🐛 Bug Fixes"
      labels: ["bug", "fix"]
    - title: "🧰 Maintenance"
      labels: ["chore"]
    - title: "📝 Other Changes"
      labels: ["*"]