// Generated by Claude Sonnet 4
package gpucheck

import (
	"testing"

	"github.com/krkn-chaos/krknctl/pkg/config"
	"github.com/stretchr/testify/assert"
)

// Helper function to create a test config
func getTestConfig() config.Config {
	return config.Config{
		QuayHost:         "quay.io",
		QuayOrg:          "krkn-chaos",
		GpuCheckRegistry: "krknctl",
		GpuCheckTag:      "gpu-check",
	}
}

func TestNewGpuChecker(t *testing.T) {
	config := getTestConfig()

	// Since we can't mock easily, just test with nil orchestrator
	checker := NewGpuChecker(nil, config)

	assert.NotNil(t, checker)
	assert.Nil(t, checker.orchestrator)
	assert.Equal(t, config, checker.config)
}

func TestParseGPUCheckOutput(t *testing.T) {
	tests := []struct {
		name     string
		output   string
		expected bool
	}{
		{
			name:     "Success indicator - GPU_CHECK_SUCCESS",
			output:   "GPU_CHECK_SUCCESS\nGPU Support: Yes",
			expected: true,
		},
		{
			name:     "Success indicator - gpu support yes",
			output:   "some log\nGPU Support: Yes\nmore log",
			expected: true,
		},
		{
			name:     "Success indicator - gpu detected",
			output:   "GPU detected via nvidia-smi",
			expected: true,
		},
		{
			name:     "Failure indicator - GPU_CHECK_FAILED",
			output:   "GPU_CHECK_FAILED\nGPU Support: No",
			expected: false,
		},
		{
			name:     "Failure indicator - gpu support no",
			output:   "some log\nGPU Support: No\nmore log",
			expected: false,
		},
		{
			name:     "Failure indicator - no gpu detected",
			output:   "No GPU detected",
			expected: false,
		},
		{
			name:     "Failure indicator - gpu not available",
			output:   "GPU not available",
			expected: false,
		},
		{
			name:     "Ambiguous output",
			output:   "some random output without clear indicators",
			expected: false,
		},
		{
			name:     "Empty output",
			output:   "",
			expected: false,
		},
		{
			name:     "Case insensitive success",
			output:   "GPU_CHECK_SUCCESS",
			expected: true,
		},
		{
			name:     "Case insensitive failure",
			output:   "GPU_CHECK_FAILED",
			expected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := parseGPUCheckOutput(tt.output)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestFormatResult(t *testing.T) {
	config := getTestConfig()
	checker := NewGpuChecker(nil, config)

	tests := []struct {
		name     string
		result   *Result
		expected string
	}{
		{
			name: "Success result",
			result: &Result{
				HasGPUSupport: true,
				Output:        "GPU_CHECK_SUCCESS",
				Error:         nil,
			},
			expected: "Yes",
		},
		{
			name: "Failure result",
			result: &Result{
				HasGPUSupport: false,
				Output:        "GPU_CHECK_FAILED",
				Error:         nil,
			},
			expected: "No",
		},
		{
			name: "Error result",
			result: &Result{
				HasGPUSupport: false,
				Output:        "",
				Error:         assert.AnError,
			},
			expected: "No",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := checker.FormatResult(tt.result)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestResult_struct(t *testing.T) {
	// Test Result struct creation and field access
	result := &Result{
		HasGPUSupport: true,
		Output:        "test output",
		Error:         nil,
	}

	assert.True(t, result.HasGPUSupport)
	assert.Equal(t, "test output", result.Output)
	assert.Nil(t, result.Error)
}

func TestGpuChecker_struct(t *testing.T) {
	config := getTestConfig()
	checker := &GpuChecker{
		orchestrator: nil,
		config:       config,
	}

	assert.Nil(t, checker.orchestrator)
	assert.Equal(t, config, checker.config)
}