// Package gpucheck provides functionality to check GPU support in container runtimes.
// Generated by Claude Sonnet 4
package gpucheck

import (
	"bytes"
	"context"
	"fmt"
	"github.com/krkn-chaos/krknctl/pkg/config"
	"github.com/krkn-chaos/krknctl/pkg/provider/models"
	"github.com/krkn-chaos/krknctl/pkg/scenarioorchestrator"
	orchestratormodels "github.com/krkn-chaos/krknctl/pkg/scenarioorchestrator/models"
	"strings"
	"time"
)

// Result represents the result of a GPU check
type Result struct {
	HasGPUSupport bool
	Output        string
	Error         error
	GPUType       string // Detected GPU type (nvidia, apple-silicon, etc.)
}

// GPUTypeDetector defines available GPU types for auto-detection
type GPUTypeDetector struct {
	Type        string
	Description string
}

// GetSupportedGPUTypes returns the list of GPU types to test in order
func GetSupportedGPUTypes() []GPUTypeDetector {
	return []GPUTypeDetector{
		{"apple-silicon", "Apple Silicon (M1, M2, M3, M4 with Metal)"},
		{"nvidia", "NVIDIA GPUs (CUDA, GeForce, Quadro, Tesla)"},
	}
}

// GpuChecker provides functionality to check GPU support
type GpuChecker struct {
	orchestrator scenarioorchestrator.ScenarioOrchestrator
	config       config.Config
}

// NewGpuChecker creates a new GPU checker instance
func NewGpuChecker(orchestrator scenarioorchestrator.ScenarioOrchestrator, config config.Config) *GpuChecker {
	return &GpuChecker{
		orchestrator: orchestrator,
		config:       config,
	}
}

// CheckGPUSupportByType runs a container to check GPU support using the GPU-type-specific image with appropriate device mounting
func (gc *GpuChecker) CheckGPUSupportByType(ctx context.Context, gpuType string, registry *models.RegistryV2) (*Result, error) {
	// Check if running on Docker runtime
	if gc.orchestrator.GetContainerRuntime() == orchestratormodels.Docker {
		return &Result{
			HasGPUSupport: false,
			Error:         fmt.Errorf("lightspeed GPU features are not available with Docker runtime - requires Podman with GPU support"),
		}, nil
	}

	// Get GPU-type-specific image URI
	image, err := gc.config.GetGpuCheckImageURIByType(gpuType)
	if err != nil {
		return &Result{
			HasGPUSupport: false,
			Error:         fmt.Errorf("failed to get GPU check image URI for type %s: %w", gpuType, err),
		}, err
	}

	// Run platform-specific GPU check using the working pattern (no device mounting to avoid macOS issues)
	result, err := gc.runPlatformGPUCheck(ctx, image, gpuType, registry)
	if result != nil {
		result.GPUType = gpuType
	}
	return result, err
}

// AutoDetectGPU automatically detects available GPU support by testing all supported GPU types
func (gc *GpuChecker) AutoDetectGPU(ctx context.Context, registry *models.RegistryV2) (*Result, error) {
	// Check if running on Docker runtime first
	if gc.orchestrator.GetContainerRuntime() == orchestratormodels.Docker {
		return &Result{
			HasGPUSupport: false,
			Error:         fmt.Errorf("lightspeed GPU features are not available with Docker runtime - requires Podman with GPU support"),
		}, nil
	}

	supportedTypes := GetSupportedGPUTypes()

	for _, gpuTypeDetector := range supportedTypes {
		fmt.Printf("🔍 Testing %s support...\n", gpuTypeDetector.Description)

		result, err := gc.CheckGPUSupportByType(ctx, gpuTypeDetector.Type, registry)
		if err != nil {
			fmt.Printf("⚠️  %s test failed: %v\n", gpuTypeDetector.Type, err)
			continue
		}

		if result.HasGPUSupport {
			fmt.Printf("✅ %s support detected!\n", gpuTypeDetector.Description)
			result.GPUType = gpuTypeDetector.Type
			return result, nil
		}

		fmt.Printf("❌ %s not available\n", gpuTypeDetector.Type)
	}

	return &Result{
		HasGPUSupport: false,
		Error:         fmt.Errorf("no GPU support found - tested: %v", getSupportedGPUTypeNames()),
	}, nil
}

// getSupportedGPUTypeNames returns a slice of supported GPU type names
func getSupportedGPUTypeNames() []string {
	types := GetSupportedGPUTypes()
	names := make([]string, len(types))
	for i, t := range types {
		names[i] = t.Type
	}
	return names
}

// runGPUCheckWithDevices runs the GPU check container with appropriate device mounting for the GPU type
func (gc *GpuChecker) runGPUCheckWithDevices(ctx context.Context, image string, gpuType string, registry *models.RegistryV2) (*Result, error) {
	// Generate unique container name
	containerName := fmt.Sprintf("krknctl-gpu-check-%s-%d", gpuType, time.Now().Unix())

	// Get GPU-specific device mounts
	deviceMounts := gc.getGPUDeviceMounts(gpuType)

	// Create buffers to capture container output
	var stdout, stderr bytes.Buffer

	// Run the GPU check container with device mounts as volume mounts
	// Note: This is a workaround since the current orchestrator doesn't support proper device mounting

	_, err := gc.orchestrator.RunAttached(image, containerName, map[string]string{}, false,
		map[string]string{}, &deviceMounts, &stdout, &stderr, nil, ctx, registry)

	if err != nil {
		return &Result{
			HasGPUSupport: false,
			Error:         fmt.Errorf("failed to run GPU check container with devices: %w", err),
		}, err
	}

	// Combine stdout and stderr
	output := stdout.String()
	if stderr.Len() > 0 {
		if output != "" {
			output += "\n"
		}
		output += stderr.String()
	}

	// Parse the output to determine GPU support
	hasGPU := parseGPUCheckOutput(output)

	return &Result{
		HasGPUSupport: hasGPU,
		Output:        output,
		Error:         nil,
	}, nil
}

// getGPUDeviceMounts returns the appropriate device mounts for the given GPU type
func (gc *GpuChecker) getGPUDeviceMounts(gpuType string) map[string]string {
	deviceMounts := make(map[string]string)

	switch gpuType {
	case "nvidia":
		// NVIDIA GPU devices
		deviceMounts["/dev/nvidia0"] = "/dev/nvidia0"
		deviceMounts["/dev/nvidiactl"] = "/dev/nvidiactl"
		deviceMounts["/dev/nvidia-uvm"] = "/dev/nvidia-uvm"
	case "amd", "intel":
		// AMD and Intel GPUs use DRI devices
		deviceMounts["/dev/dri"] = "/dev/dri"
	case "apple-silicon":
		// Apple Silicon GPUs (via libkrun) use DRI devices
		deviceMounts["/dev/dri"] = "/dev/dri"
	}

	return deviceMounts
}

// runPlatformGPUCheck runs the platform-specific GPU check container using the working pattern
func (gc *GpuChecker) runPlatformGPUCheck(ctx context.Context, image string, gpuType string, registry *models.RegistryV2) (*Result, error) {
	// Generate unique container name
	containerName := fmt.Sprintf("krknctl-gpu-check-%s-%d", gpuType, time.Now().Unix())

	// Create buffers to capture container output
	var stdout, stderr bytes.Buffer

	// Use the working pattern (no device mounting to avoid macOS issues)
	emptyDevices := make(map[string]string)
	_, err := scenarioorchestrator.CommonRunAttached(
		image,
		containerName,
		map[string]string{}, // No special environment variables needed
		false,               // Don't cache
		map[string]string{}, // No volume mounts 
		&emptyDevices,       // Empty devices to avoid macOS issues
		&stdout,
		&stderr,
		gc.orchestrator,
		nil, // No communication channel needed
		ctx,
		registry,
	)

	if err != nil {
		return &Result{
			HasGPUSupport: false,
			Error:         fmt.Errorf("failed to run %s GPU check container: %w", gpuType, err),
		}, err
	}

	// Combine stdout and stderr
	output := stdout.String()
	if stderr.Len() > 0 {
		if output != "" {
			output += "\n"
		}
		output += stderr.String()
	}

	// Parse the output to determine GPU support
	hasGPU := parseGPUCheckOutput(output)
	
	// Extract GPU type from output manually
	detectedGPUType := ""
	if hasGPU {
		lines := strings.Split(output, "\n")
		for _, line := range lines {
			line = strings.TrimSpace(line)
			if strings.HasPrefix(line, "GPU_TYPE=") {
				detectedGPUType = strings.TrimPrefix(line, "GPU_TYPE=")
				detectedGPUType = strings.ToLower(detectedGPUType)
				// Convert script GPU types to our naming convention
				switch detectedGPUType {
				case "nvidia":
					detectedGPUType = "nvidia"
				case "apple":
					detectedGPUType = "apple-silicon"
				case "amd":
					detectedGPUType = "amd"
				case "intel":
					detectedGPUType = "intel"
				}
				break
			}
		}
	}

	return &Result{
		HasGPUSupport: hasGPU,
		Output:        output,
		Error:         nil,
		GPUType:       detectedGPUType,
	}, nil
}

// parseGPUCheckOutput parses the container output to determine if GPU support is available
func parseGPUCheckOutput(output string) bool {
	// Look for success indicators in the output
	output = strings.ToLower(strings.TrimSpace(output))

	// Check for negative indicators first to handle cases like "no gpu detected"
	if strings.Contains(output, "gpu_check_failed") ||
		strings.Contains(output, "gpu support: no") ||
		strings.Contains(output, "no gpu detected") ||
		strings.Contains(output, "gpu not available") {
		return false
	}

	// Check for positive indicators
	if strings.Contains(output, "gpu_check_success") ||
		strings.Contains(output, "gpu support: yes") ||
		strings.Contains(output, "gpu detected") {
		return true
	}

	// Default to false if output is ambiguous
	return false
}

// getGPUDescription returns a human-readable description for a GPU type
func getGPUDescription(gpuType string) string {
	descriptions := map[string]string{
		"nvidia":        "NVIDIA GPU (CUDA, GeForce, Quadro, Tesla)",
		"amd":           "AMD GPU (Radeon, FirePro, Instinct with ROCm)",
		"intel":         "Intel GPU (Arc, Iris, UHD Graphics)",
		"apple-silicon": "Apple Silicon GPU (M1, M2, M3, M4 with Metal)",
		"generic":       "Generic GPU support",
		"runtime":       "GPU support via runtime environment",
	}
	
	if desc, exists := descriptions[gpuType]; exists {
		return desc
	}
	return fmt.Sprintf("Unknown GPU type: %s", gpuType)
}

// FormatResult formats the GPU check result for CLI output
func (gc *GpuChecker) FormatResult(result *Result) string {
	if result.Error != nil {
		return fmt.Sprintf("GPU Support: No\n\nError occurred during GPU check: %v\n\n⚠️  Container runtime does not support GPU acceleration.\nThis environment is not suitable for running krknctl lightspeed workloads.\n\nTo enable GPU support:\n• For NVIDIA GPUs: Install nvidia-container-toolkit and configure your container runtime\n• For AMD GPUs: Install ROCm and configure appropriate device access\n• For Intel GPUs: Ensure proper device permissions and Intel GPU drivers\n• For Apple Silicon (M1/M2/M3): Create Podman machine with libkrun for virtualized GPU\n  See: https://podman-desktop.io/docs/podman/gpu", result.Error)
	}

	if result.HasGPUSupport {
		gpuInfo := ""
		if result.GPUType != "" {
			gpuDescription := getGPUDescription(result.GPUType)
			gpuInfo = fmt.Sprintf("\nDetected GPU: %s", gpuDescription)
		}
		return fmt.Sprintf("GPU Support: Yes%s\n\n✅ Container runtime has GPU acceleration available.\nThis environment is suitable for running krknctl lightspeed workloads.", gpuInfo)
	}

	return "GPU Support: No\n\n⚠️  Container runtime does not support GPU acceleration.\nThis environment is not suitable for running krknctl lightspeed workloads.\n\nTo enable GPU support:\n• For NVIDIA GPUs: Install nvidia-container-toolkit and configure your container runtime\n• For AMD GPUs: Install ROCm and configure appropriate device access\n• For Intel GPUs: Ensure proper device permissions and Intel GPU drivers\n• For Apple Silicon (M1/M2/M3): Create Podman machine with libkrun for virtualized GPU\n  Note: Only supports Vulkan compute shaders, not Metal framework\n  See: https://podman-desktop.io/docs/podman/gpu\n\nFor more information, refer to your container runtime's GPU configuration documentation."
}
