// Package gpucheck provides functionality to check GPU support in container runtimes.
// Generated by Claude Sonnet 4
package gpucheck

import (
	"bytes"
	"context"
	"fmt"
	"github.com/krkn-chaos/krknctl/pkg/config"
	"github.com/krkn-chaos/krknctl/pkg/provider/models"
	"github.com/krkn-chaos/krknctl/pkg/scenarioorchestrator"
	"strings"
	"time"
)

// Result represents the result of a GPU check
type Result struct {
	HasGPUSupport bool
	Output        string
	Error         error
}

// GpuChecker provides functionality to check GPU support
type GpuChecker struct {
	orchestrator scenarioorchestrator.ScenarioOrchestrator
	config       config.Config
}

// NewGpuChecker creates a new GPU checker instance
func NewGpuChecker(orchestrator scenarioorchestrator.ScenarioOrchestrator, config config.Config) *GpuChecker {
	return &GpuChecker{
		orchestrator: orchestrator,
		config:       config,
	}
}

// CheckGPUSupport runs a container to check GPU support in the container runtime
func (gc *GpuChecker) CheckGPUSupport(ctx context.Context, customImage string, registry *models.RegistryV2) (*Result, error) {
	// Determine which image to use
	image := customImage
	if image == "" {
		defaultImage, err := gc.config.GetGpuCheckImageURI()
		if err != nil {
			return &Result{
				HasGPUSupport: false,
				Error:         fmt.Errorf("failed to get default GPU check image URI: %w", err),
			}, err
		}
		image = defaultImage
	}

	// Generate unique container name
	containerName := fmt.Sprintf("krknctl-gpu-check-%d", time.Now().Unix())

	// Create buffers to capture container output
	var stdout, stderr bytes.Buffer

	// Run the GPU check container with output capture
	_, err := scenarioorchestrator.CommonRunAttached(
		image,
		containerName,
		map[string]string{}, // No special environment variables needed
		false,               // Don't cache
		map[string]string{}, // No volume mounts needed
		&stdout,
		&stderr,
		gc.orchestrator,
		nil, // No communication channel needed for this use case
		ctx,
		registry,
	)

	if err != nil {
		return &Result{
			HasGPUSupport: false,
			Error:         fmt.Errorf("failed to run GPU check container: %w", err),
		}, err
	}

	// Combine stdout and stderr
	output := stdout.String()
	if stderr.Len() > 0 {
		if output != "" {
			output += "\n"
		}
		output += stderr.String()
	}

	// Parse the output to determine GPU support
	hasGPU := parseGPUCheckOutput(output)

	return &Result{
		HasGPUSupport: hasGPU,
		Output:        output,
		Error:         nil,
	}, nil
}

// parseGPUCheckOutput parses the container output to determine if GPU support is available
func parseGPUCheckOutput(output string) bool {
	// Look for success indicators in the output
	output = strings.ToLower(strings.TrimSpace(output))

	// Check for negative indicators first to handle cases like "no gpu detected"
	if strings.Contains(output, "gpu_check_failed") ||
		strings.Contains(output, "gpu support: no") ||
		strings.Contains(output, "no gpu detected") ||
		strings.Contains(output, "gpu not available") {
		return false
	}

	// Check for positive indicators
	if strings.Contains(output, "gpu_check_success") ||
		strings.Contains(output, "gpu support: yes") ||
		strings.Contains(output, "gpu detected") {
		return true
	}

	// Default to false if output is ambiguous
	return false
}

// FormatResult formats the GPU check result for CLI output
func (gc *GpuChecker) FormatResult(result *Result) string {
	if result.Error != nil {
		return fmt.Sprintf("GPU Support: No\n\nError occurred during GPU check: %v\n\n⚠️  Container runtime does not support GPU acceleration.\nThis environment is not suitable for running krknctl lightspeed workloads.\n\nTo enable GPU support:\n• For NVIDIA GPUs: Install nvidia-container-toolkit and configure your container runtime\n• For AMD GPUs: Install ROCm and configure appropriate device access\n• For Intel GPUs: Ensure proper device permissions and Intel GPU drivers\n• For Apple Silicon (M1/M2/M3): Create Podman machine with libkrun for virtualized GPU\n  See: https://podman-desktop.io/docs/podman/gpu", result.Error)
	}

	if result.HasGPUSupport {
		return "GPU Support: Yes\n\n✅ Container runtime has GPU acceleration available.\nThis environment is suitable for running krknctl lightspeed workloads."
	}

	return "GPU Support: No\n\n⚠️  Container runtime does not support GPU acceleration.\nThis environment is not suitable for running krknctl lightspeed workloads.\n\nTo enable GPU support:\n• For NVIDIA GPUs: Install nvidia-container-toolkit and configure your container runtime\n• For AMD GPUs: Install ROCm and configure appropriate device access\n• For Intel GPUs: Ensure proper device permissions and Intel GPU drivers\n• For Apple Silicon (M1/M2/M3): Create Podman machine with libkrun for virtualized GPU\n  Note: Only supports Vulkan compute shaders, not Metal framework\n  See: https://podman-desktop.io/docs/podman/gpu\n\nFor more information, refer to your container runtime's GPU configuration documentation."
}
