// Generated by Claude Sonnet 4
package cmd

import (
	"fmt"
	"github.com/krkn-chaos/krknctl/pkg/config"
	"github.com/krkn-chaos/krknctl/pkg/gpucheck"
	"github.com/krkn-chaos/krknctl/pkg/provider/factory"
	"github.com/krkn-chaos/krknctl/pkg/provider/models"
	"github.com/krkn-chaos/krknctl/pkg/scenarioorchestrator"
	"github.com/spf13/cobra"
)

func NewLightspeedCommand() *cobra.Command {
	var command = &cobra.Command{
		Use:   "lightspeed",
		Short: "GPU and acceleration related utilities",
		Long:  `GPU and acceleration related utilities for container runtime environments`,
	}

	return command
}

func NewLightspeedCheckCommand(
	providerFactory *factory.ProviderFactory,
	scenarioOrchestrator *scenarioorchestrator.ScenarioOrchestrator,
	config config.Config,
) *cobra.Command {
	var command = &cobra.Command{
		Use:   "check",
		Short: "Check GPU support in container runtime",
		Long:  `Check whether the container runtime (Podman or Docker) has GPU support available`,
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Get the image flag value
			image, err := cmd.Flags().GetString("image")
			if err != nil {
				return fmt.Errorf("failed to get image flag: %w", err)
			}

			// Print container runtime info
			(*scenarioOrchestrator).PrintContainerRuntime()

			// Get container runtime socket
			socket, err := (*scenarioOrchestrator).GetContainerRuntimeSocket(nil)
			if err != nil {
				return fmt.Errorf("failed to get container runtime socket: %w", err)
			}

			// Connect to container runtime
			ctx, err := (*scenarioOrchestrator).Connect(*socket)
			if err != nil {
				return fmt.Errorf("failed to connect to container runtime: %w", err)
			}

			// Build registry configuration from flags and environment
			registry, err := buildRegistryFromFlags(cmd, providerFactory, config)
			if err != nil {
				return fmt.Errorf("failed to build registry configuration: %w", err)
			}

			// Create GPU checker
			gpuChecker := gpucheck.NewGpuChecker(*scenarioOrchestrator, config)

			// Run GPU check
			result, err := gpuChecker.CheckGPUSupport(ctx, image, registry)
			if err != nil {
				return fmt.Errorf("failed to check GPU support: %w", err)
			}

			// Format and print result
			fmt.Println(gpuChecker.FormatResult(result))

			return nil
		},
	}

	// Add image flag
	command.Flags().String("image", "", "custom GPU check container image (defaults to config value)")

	return command
}

// buildRegistryFromFlags builds registry configuration from command flags and environment
func buildRegistryFromFlags(cmd *cobra.Command, providerFactory *factory.ProviderFactory, config config.Config) (*models.RegistryV2, error) {
	// Get private registry flags from parent command
	privateRegistry, _ := cmd.Flags().GetString("private-registry")
	privateRegistryUsername, _ := cmd.Flags().GetString("private-registry-username")
	privateRegistryPassword, _ := cmd.Flags().GetString("private-registry-password")
	privateRegistryToken, _ := cmd.Flags().GetString("private-registry-token")
	privateRegistryInsecure, _ := cmd.Flags().GetBool("private-registry-insecure")
	privateRegistrySkipTLS, _ := cmd.Flags().GetBool("private-registry-skip-tls")

	// If no private registry is specified, return nil (use default public registry)
	if privateRegistry == "" {
		return nil, nil
	}

	// Build registry configuration
	registry := &models.RegistryV2{
		RegistryURL:        privateRegistry,
		Username:           &privateRegistryUsername,
		Password:           &privateRegistryPassword,
		Token:              &privateRegistryToken,
		Insecure:           privateRegistryInsecure,
		SkipTLS:            privateRegistrySkipTLS,
		ScenarioRepository: "", // Empty for GPU check since we use full image path
	}

	return registry, nil
}