// Generated by Claude Sonnet 4
package cmd

import (
	"github.com/spf13/cobra"
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestNewLightspeedCommand(t *testing.T) {
	cmd := NewLightspeedCommand()
	
	assert.NotNil(t, cmd)
	assert.Equal(t, "lightspeed", cmd.Use)
	assert.Contains(t, cmd.Short, "GPU and acceleration")
	assert.Contains(t, cmd.Long, "GPU and acceleration related utilities")
}

func TestNewLightspeedCheckCommand(t *testing.T) {
	config := getConfig(t)
	providerFactory := getProviderFactory(t)
	orchestrator := getOrchestrator(t)
	
	cmd := NewLightspeedCheckCommand(providerFactory, &orchestrator, config)
	
	assert.NotNil(t, cmd)
	assert.Equal(t, "check", cmd.Use)
	assert.Contains(t, cmd.Short, "Check GPU support")
	assert.Contains(t, cmd.Long, "Check whether the container runtime")
	assert.NotNil(t, cmd.Args)
	
	// Check that the image flag exists
	imageFlag := cmd.Flags().Lookup("image")
	assert.NotNil(t, imageFlag)
	assert.Equal(t, "string", imageFlag.Value.Type())
	assert.Contains(t, imageFlag.Usage, "custom GPU check container image")
}

func TestBuildRegistryFromFlags_NoPrivateRegistry(t *testing.T) {
	cmd := &cobra.Command{}
	config := getConfig(t)
	providerFactory := getProviderFactory(t)
	
	// Add all the required flags but don't set private-registry
	cmd.Flags().String("private-registry", "", "")
	cmd.Flags().String("private-registry-username", "", "")
	cmd.Flags().String("private-registry-password", "", "")
	cmd.Flags().String("private-registry-token", "", "")
	cmd.Flags().Bool("private-registry-insecure", false, "")
	cmd.Flags().Bool("private-registry-skip-tls", false, "")
	
	registry, err := buildRegistryFromFlags(cmd, providerFactory, config)
	
	assert.NoError(t, err)
	assert.Nil(t, registry)
}

func TestBuildRegistryFromFlags_WithPrivateRegistry(t *testing.T) {
	cmd := &cobra.Command{}
	config := getConfig(t)
	providerFactory := getProviderFactory(t)
	
	// Add and set all the required flags
	cmd.Flags().String("private-registry", "registry.example.com", "")
	cmd.Flags().String("private-registry-username", "testuser", "")
	cmd.Flags().String("private-registry-password", "testpass", "")
	cmd.Flags().String("private-registry-token", "testtoken", "")
	cmd.Flags().Bool("private-registry-insecure", true, "")
	cmd.Flags().Bool("private-registry-skip-tls", true, "")
	
	// Set the flag values
	cmd.Flags().Set("private-registry", "registry.example.com")
	cmd.Flags().Set("private-registry-username", "testuser")
	cmd.Flags().Set("private-registry-password", "testpass")
	cmd.Flags().Set("private-registry-token", "testtoken")
	cmd.Flags().Set("private-registry-insecure", "true")
	cmd.Flags().Set("private-registry-skip-tls", "true")
	
	registry, err := buildRegistryFromFlags(cmd, providerFactory, config)
	
	assert.NoError(t, err)
	assert.NotNil(t, registry)
	assert.Equal(t, "registry.example.com", registry.RegistryURL)
	assert.Equal(t, "testuser", *registry.Username)
	assert.Equal(t, "testpass", *registry.Password)
	assert.Equal(t, "testtoken", *registry.Token)
	assert.True(t, registry.Insecure)
	assert.True(t, registry.SkipTLS)
	assert.Equal(t, "", registry.ScenarioRepository)
}

func TestBuildRegistryFromFlags_PartialConfiguration(t *testing.T) {
	cmd := &cobra.Command{}
	config := getConfig(t)
	providerFactory := getProviderFactory(t)
	
	// Add flags and set only some values
	cmd.Flags().String("private-registry", "registry.example.com", "")
	cmd.Flags().String("private-registry-username", "testuser", "")
	cmd.Flags().String("private-registry-password", "", "")
	cmd.Flags().String("private-registry-token", "", "")
	cmd.Flags().Bool("private-registry-insecure", false, "")
	cmd.Flags().Bool("private-registry-skip-tls", false, "")
	
	// Set only some flag values
	cmd.Flags().Set("private-registry", "registry.example.com")
	cmd.Flags().Set("private-registry-username", "testuser")
	
	registry, err := buildRegistryFromFlags(cmd, providerFactory, config)
	
	assert.NoError(t, err)
	assert.NotNil(t, registry)
	assert.Equal(t, "registry.example.com", registry.RegistryURL)
	assert.Equal(t, "testuser", *registry.Username)
	assert.Equal(t, "", *registry.Password)
	assert.Equal(t, "", *registry.Token)
	assert.False(t, registry.Insecure)
	assert.False(t, registry.SkipTLS)
}

func TestLightspeedCheckCommand_Integration(t *testing.T) {
	config := getConfig(t)
	providerFactory := getProviderFactory(t)
	orchestrator := getOrchestrator(t)
	
	// Create lightspeed command structure
	lightspeedCmd := NewLightspeedCommand()
	lightspeedCheckCmd := NewLightspeedCheckCommand(providerFactory, &orchestrator, config)
	lightspeedCmd.AddCommand(lightspeedCheckCmd)
	
	// Test command structure
	assert.NotNil(t, lightspeedCmd)
	assert.Equal(t, 1, len(lightspeedCmd.Commands()))
	
	checkCmd := lightspeedCmd.Commands()[0]
	assert.Equal(t, "check", checkCmd.Use)
	
	// Test that the image flag can be set
	err := checkCmd.Flags().Set("image", "custom-image:latest")
	assert.NoError(t, err)
	
	imageValue, err := checkCmd.Flags().GetString("image")
	assert.NoError(t, err)
	assert.Equal(t, "custom-image:latest", imageValue)
}

func TestLightspeedCommand_FlagInheritance(t *testing.T) {
	config := getConfig(t)
	providerFactory := getProviderFactory(t)
	orchestrator := getOrchestrator(t)
	
	// Create root command with global flags
	rootCmd := NewRootCommand(config)
	rootCmd.PersistentFlags().String("private-registry", "", "private registry URI")
	rootCmd.PersistentFlags().String("private-registry-username", "", "private registry username")
	rootCmd.PersistentFlags().String("private-registry-password", "", "private registry password")
	rootCmd.PersistentFlags().Bool("private-registry-insecure", false, "uses plain HTTP instead of TLS")
	rootCmd.PersistentFlags().Bool("private-registry-skip-tls", false, "skips tls verification")
	rootCmd.PersistentFlags().String("private-registry-token", "", "private registry token")
	
	// Add lightspeed commands
	lightspeedCmd := NewLightspeedCommand()
	lightspeedCheckCmd := NewLightspeedCheckCommand(providerFactory, &orchestrator, config)
	lightspeedCmd.AddCommand(lightspeedCheckCmd)
	rootCmd.AddCommand(lightspeedCmd)
	
	// Test that global flags are inherited
	assert.NotNil(t, rootCmd.PersistentFlags().Lookup("private-registry"))
	assert.NotNil(t, lightspeedCheckCmd.Flags().Lookup("image"))
	
	// Test setting flags
	err := rootCmd.PersistentFlags().Set("private-registry", "test-registry.com")
	assert.NoError(t, err)
	
	registryValue, err := rootCmd.PersistentFlags().GetString("private-registry")
	assert.NoError(t, err)
	assert.Equal(t, "test-registry.com", registryValue)
}

// Test helper functions for command creation
func TestCommandCreationHelpers(t *testing.T) {
	config := getConfig(t)
	providerFactory := getProviderFactory(t)
	orchestrator := getOrchestrator(t)
	
	// Test that all required parameters are properly used
	lightspeedCmd := NewLightspeedCommand()
	assert.NotNil(t, lightspeedCmd)
	
	checkCmd := NewLightspeedCheckCommand(providerFactory, &orchestrator, config)
	assert.NotNil(t, checkCmd)
	
	// Verify command has proper run function
	assert.NotNil(t, checkCmd.RunE)
	
	// Verify command has args validation function
	assert.NotNil(t, checkCmd.Args)
}

// Test registry building edge cases
func TestBuildRegistryFromFlags_EmptyStrings(t *testing.T) {
	cmd := &cobra.Command{}
	config := getConfig(t)
	providerFactory := getProviderFactory(t)
	
	// Add flags with empty string values
	cmd.Flags().String("private-registry", "registry.example.com", "")
	cmd.Flags().String("private-registry-username", "", "")
	cmd.Flags().String("private-registry-password", "", "")
	cmd.Flags().String("private-registry-token", "", "")
	cmd.Flags().Bool("private-registry-insecure", false, "")
	cmd.Flags().Bool("private-registry-skip-tls", false, "")
	
	cmd.Flags().Set("private-registry", "registry.example.com")
	// Leave other flags as empty strings
	
	registry, err := buildRegistryFromFlags(cmd, providerFactory, config)
	
	assert.NoError(t, err)
	assert.NotNil(t, registry)
	assert.Equal(t, "registry.example.com", registry.RegistryURL)
	assert.Equal(t, "", *registry.Username)
	assert.Equal(t, "", *registry.Password)
	assert.Equal(t, "", *registry.Token)
}

// Test command validation
func TestLightspeedCheckCommand_Validation(t *testing.T) {
	config := getConfig(t)
	providerFactory := getProviderFactory(t)
	orchestrator := getOrchestrator(t)
	
	cmd := NewLightspeedCheckCommand(providerFactory, &orchestrator, config)
	
	// Test that command has required fields
	assert.NotEmpty(t, cmd.Use)
	assert.NotEmpty(t, cmd.Short)
	assert.NotEmpty(t, cmd.Long)
	assert.NotNil(t, cmd.RunE)
	
	// Test command flags
	flags := cmd.Flags()
	assert.NotNil(t, flags)
	
	imageFlag := flags.Lookup("image")
	assert.NotNil(t, imageFlag)
	assert.Equal(t, "", imageFlag.DefValue) // Should default to empty string
}