// Generated by Claude Code
// RAG model deployment functions for krknctl lightspeed

package cmd

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/krkn-chaos/krknctl/pkg/config"
	"github.com/krkn-chaos/krknctl/pkg/provider/models"
	"github.com/krkn-chaos/krknctl/pkg/scenarioorchestrator"
)

// RAGDeploymentResult holds information about the deployed RAG model
type RAGDeploymentResult struct {
	containerID string
	hostPort    string
}

// deployRAGModel deploys the RAG model container in detached mode with proper port mapping
func deployRAGModel(ctx context.Context, gpuType string, offline bool, orchestrator scenarioorchestrator.ScenarioOrchestrator, config config.Config, registry *models.RegistryV2) (*RAGDeploymentResult, error) {
	// Get RAG model image URI
	ragImageURI, err := config.GetRAGModelImageURI()
	if err != nil {
		return nil, fmt.Errorf("failed to get RAG model image URI: %w", err)
	}

	// Generate unique container name using config
	containerName := fmt.Sprintf("%s-%d", config.RAGContainerPrefix, time.Now().Unix())

	// Set up environment variables
	env := map[string]string{}
	if offline {
		env["USE_OFFLINE"] = "true"
	} else {
		env["USE_OFFLINE"] = "false"
	}

	// Set up GPU device mounts
	deviceMounts := getRAGGPUDeviceMounts(gpuType)

	// Set up port mapping using config
	hostPort := config.RAGServicePort
	portMappings := &map[string]string{
		hostPort: config.RAGServicePort, // host:container
	}

	// Run the RAG container in detached mode
	containerID, err := orchestrator.Run(
		ragImageURI,
		containerName,
		env,
		false,        // Don't cache
		deviceMounts, // GPU device mounts
		nil,          // No communication channel for detached
		ctx,
		registry,
		portMappings, // Port mappings
	)

	if err != nil {
		return nil, fmt.Errorf("failed to run RAG container: %w", err)
	}

	fmt.Printf("🚀 RAG container started: %s\n", *containerID)
	fmt.Printf("📡 Port mapping: %s:%s -> container:%s\n", config.RAGHost, hostPort, config.RAGServicePort)

	return &RAGDeploymentResult{
		containerID: *containerID,
		hostPort:    hostPort,
	}, nil
}

// getRAGGPUDeviceMounts returns device mounts for RAG container (similar to GPU check)
func getRAGGPUDeviceMounts(gpuType string) map[string]string {
	deviceMounts := make(map[string]string)

	switch gpuType {
	case "nvidia":
		// NVIDIA GPU devices
		deviceMounts["/dev/nvidia0"] = "/dev/nvidia0"
		deviceMounts["/dev/nvidiactl"] = "/dev/nvidiactl"
		deviceMounts["/dev/nvidia-uvm"] = "/dev/nvidia-uvm"
	// Temporarily disabled GPU types
	// case "amd", "intel":
	//	// AMD and Intel GPUs use DRI devices
	//	deviceMounts["/dev/dri"] = "/dev/dri"
	case "apple-silicon":
		// Apple Silicon GPUs (via libkrun) use DRI devices
		deviceMounts["/dev/dri"] = "/dev/dri"
	}

	return deviceMounts
}

// HealthResponse represents the health check response
type HealthResponse struct {
	Status           string `json:"status"`
	Service          string `json:"service"`
	Model            string `json:"model"`
	DocumentsIndexed int    `json:"documents_indexed"`
}

// performRAGHealthCheck performs health checking with timeout and cleanup on failure
func performRAGHealthCheck(containerID string, hostPort string, orchestrator scenarioorchestrator.ScenarioOrchestrator, ctx context.Context, config config.Config) (bool, error) {
	// Health URL is constructed from trusted config values and validated port
	healthURL := fmt.Sprintf("http://%s:%s%s", config.RAGHost, hostPort, config.RAGHealthEndpoint)
	maxRetries := config.RAGHealthMaxRetries
	retryInterval := time.Duration(config.RAGHealthRetryIntervalSeconds) * time.Second

	fmt.Printf("🩺 Health checking RAG service at %s...\n", healthURL)

	for i := 0; i < maxRetries; i++ {
		// Check if container is still running
		containers, err := orchestrator.ListRunningContainers(ctx)
		if err != nil {
			fmt.Printf("⚠️  Warning: failed to list containers: %v\n", err)
		} else {
			containerFound := false
			if containers != nil {
				for _, container := range *containers {
					if container.ID == containerID {
						containerFound = true
						break
					}
				}
			}
			if !containerFound {
				return false, fmt.Errorf("container %s is no longer running", containerID)
			}
		}

		// Perform health check - URL is safe as it's constructed from config
		// #nosec G107 - URL constructed from trusted configuration
		resp, err := http.Get(healthURL)
		if err == nil && resp.StatusCode == 200 {
			var health HealthResponse
			if err := json.NewDecoder(resp.Body).Decode(&health); err == nil {
				if closeErr := resp.Body.Close(); closeErr != nil {
					fmt.Printf("⚠️  Warning: failed to close response body: %v\n", closeErr)
				}
				if health.Status == "healthy" {
					fmt.Printf("✅ Service healthy: %s with %d documents indexed\n", health.Model, health.DocumentsIndexed)
					return true, nil
				}
			}
			if closeErr := resp.Body.Close(); closeErr != nil {
				fmt.Printf("⚠️  Warning: failed to close response body: %v\n", closeErr)
			}
		}

		if i < maxRetries-1 {
			fmt.Printf("⏳ Waiting for service to become ready... (%d/%d)\n", i+1, maxRetries)
			time.Sleep(retryInterval)
		}
	}

	// Health check failed, clean up the container
	timeoutMinutes := (maxRetries * config.RAGHealthRetryIntervalSeconds) / 60
	fmt.Printf("❌ Health check timed out after %d minutes, cleaning up container...\n", timeoutMinutes)
	if err := orchestrator.Kill(&containerID, ctx); err != nil {
		fmt.Printf("⚠️  Warning: failed to clean up container %s: %v\n", containerID, err)
	}

	return false, fmt.Errorf("service did not become healthy within timeout")
}

// QueryRequest represents a request to the RAG service
type QueryRequest struct {
	Query      string `json:"query"`
	MaxResults int    `json:"max_results"`
	Stream     bool   `json:"stream"`
}

// QueryResponse represents a response from the RAG service
type QueryResponse struct {
	Response string                   `json:"response"`
	Sources  []map[string]interface{} `json:"sources"`
	Query    string                   `json:"query"`
}

// startInteractivePrompt starts an interactive chat session with the RAG service
func startInteractivePrompt(containerID string, hostPort string, orchestrator scenarioorchestrator.ScenarioOrchestrator, ctx context.Context, config config.Config) error {
	scanner := bufio.NewScanner(os.Stdin)
	
	fmt.Printf("🤖 AI Assistant ready! Ask me about krknctl commands or chaos engineering:\n")
	fmt.Printf("📍 Service available at: http://%s:%s\n", config.RAGHost, hostPort)
	fmt.Printf("💡 Try asking: 'How do I run a pod deletion scenario?'\n")
	fmt.Printf("🚪 Type 'exit' or 'quit' to stop.\n\n")
	
	for {
		fmt.Print("> ")
		if !scanner.Scan() {
			break
		}
		
		query := strings.TrimSpace(scanner.Text())
		if query == "" {
			continue
		}
		
		if strings.ToLower(query) == "exit" || strings.ToLower(query) == "quit" {
			fmt.Println("👋 Goodbye!")
			break
		}
		
		// Send query to RAG service
		response, err := queryRAGService(hostPort, query, config)
		if err != nil {
			fmt.Printf("❌ Error: %v\n", err)
			fmt.Printf("💡 Tip: Make sure the service is fully initialized. Large models may take a few minutes.\n")
			continue
		}
		
		// Display response
		fmt.Printf("\n🤖 %s\n", response.Response)
		
		// Display sources if available
		if len(response.Sources) > 0 {
			fmt.Println("\n📚 Sources:")
			for i, source := range response.Sources {
				if title, ok := source["title"].(string); ok {
					if url, ok := source["url"].(string); ok {
						fmt.Printf("  %d. %s (%s)\n", i+1, title, url)
					} else {
						fmt.Printf("  %d. %s\n", i+1, title)
					}
				}
			}
		}
		fmt.Println()
	}
	
	if err := scanner.Err(); err != nil {
		return fmt.Errorf("error reading input: %w", err)
	}
	
	// Clean up: stop the container
	fmt.Println("\n🧹 Cleaning up RAG service...")
	if err := orchestrator.Kill(&containerID, ctx); err != nil {
		fmt.Printf("⚠️  Warning: failed to stop RAG container: %v\n", err)
	} else {
		fmt.Println("✅ RAG service stopped successfully")
	}
	
	return nil
}

// queryRAGService sends a query to the RAG service and returns the response
func queryRAGService(hostPort string, query string, config config.Config) (*QueryResponse, error) {
	// Query URL is constructed from trusted config values and validated port
	url := fmt.Sprintf("http://%s:%s%s", config.RAGHost, hostPort, config.RAGQueryEndpoint)

	requestBody := QueryRequest{
		Query:      query,
		MaxResults: config.RAGQueryMaxResults,
		Stream:     false,
	}

	jsonData, err := json.Marshal(requestBody)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// #nosec G107 - URL constructed from trusted configuration
	resp, err := http.Post(url, "application/json", bytes.NewBuffer(jsonData))
	if err != nil {
		return nil, fmt.Errorf("failed to send request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		body, _ := io.ReadAll(resp.Body)
		return nil, fmt.Errorf("service returned error %d: %s", resp.StatusCode, string(body))
	}

	var response QueryResponse
	if err := json.NewDecoder(resp.Body).Decode(&response); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &response, nil
}