// Generated by Claude Sonnet 4
package config

import (
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestLoadConfig(t *testing.T) {
	config, err := LoadConfig()

	assert.NoError(t, err)
	assert.NotNil(t, config)

	// Test that basic required fields are present
	assert.NotEmpty(t, config.Version)
	assert.NotEmpty(t, config.QuayHost)
	assert.NotEmpty(t, config.QuayOrg)
	assert.NotEmpty(t, config.QuayScenarioRegistry)
	assert.NotEmpty(t, config.QuayBaseImageRegistry)
	assert.NotEmpty(t, config.QuayBaseImageTag)

	// Test assist specific fields that were added
	assert.NotEmpty(t, config.AssistRegistry)
	assert.NotEmpty(t, config.AssistModelTagApple)
	assert.NotEmpty(t, config.AssistModelTagIntel)
	assert.Equal(t, "krknctl-assist", config.AssistRegistry)
	assert.Equal(t, "apple-silicon", config.AssistModelTagApple)
	assert.Equal(t, "intel", config.AssistModelTagIntel)
}

func TestGetQuayImageURI(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	uri, err := config.GetQuayImageURI()
	assert.NoError(t, err)
	assert.NotEmpty(t, uri)

	// Should contain the host, org, and scenario registry
	assert.Contains(t, uri, config.QuayHost)
	assert.Contains(t, uri, config.QuayOrg)
	assert.Contains(t, uri, config.QuayScenarioRegistry)

	// Should be in the format: host/org/registry
	expected := config.QuayHost + "/" + config.QuayOrg + "/" + config.QuayScenarioRegistry
	assert.Equal(t, expected, uri)
}

func TestGetCustomDomainImageURI(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	uri, err := config.GetCustomDomainImageURI()
	assert.NoError(t, err)
	assert.NotEmpty(t, uri)

	// Should contain the custom domain host, org, and scenario registry
	assert.Contains(t, uri, config.CustomDomainHost)
	assert.Contains(t, uri, config.QuayOrg)
	assert.Contains(t, uri, config.QuayScenarioRegistry)

	// Should be in the format: custom_host/org/registry
	expected := config.CustomDomainHost + "/" + config.QuayOrg + "/" + config.QuayScenarioRegistry
	assert.Equal(t, expected, uri)
}

func TestGetQuayScenarioRepositoryAPIURI(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	uri, err := config.GetQuayScenarioRepositoryAPIURI()
	assert.NoError(t, err)
	assert.NotEmpty(t, uri)

	// Should be a valid HTTPS URL
	assert.Contains(t, uri, "https://")
	assert.Contains(t, uri, config.QuayHost)
	assert.Contains(t, uri, config.QuayRepositoryAPI)
	assert.Contains(t, uri, config.QuayOrg)
	assert.Contains(t, uri, config.QuayScenarioRegistry)
}

func TestGetQuayBaseImageRepositoryAPIURI(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	uri, err := config.GetQuayBaseImageRepositoryAPIURI()
	assert.NoError(t, err)
	assert.NotEmpty(t, uri)

	// Should be a valid HTTPS URL
	assert.Contains(t, uri, "https://")
	assert.Contains(t, uri, config.QuayHost)
	assert.Contains(t, uri, config.QuayRepositoryAPI)
	assert.Contains(t, uri, config.QuayOrg)
	assert.Contains(t, uri, config.QuayBaseImageRegistry)
}

func TestGetAssistImageURI(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	uri, err := config.GetAssistImageURI()
	assert.NoError(t, err)
	assert.NotEmpty(t, uri)

	// Should contain the host, org, and assist registry
	assert.Contains(t, uri, config.QuayHost)
	assert.Contains(t, uri, config.QuayOrg)
	assert.Contains(t, uri, config.AssistRegistry)

	// Tag depends on platform - either apple-silicon or intel
	assert.True(t, strings.Contains(uri, config.AssistModelTagApple) ||
		strings.Contains(uri, config.AssistModelTagIntel),
		"URI should contain either apple-silicon or intel tag")

	// Verify base format (without tag assertion since it's platform-specific)
	baseURI := config.QuayHost + "/" + config.QuayOrg + "/" + config.AssistRegistry
	assert.Contains(t, uri, baseURI)
}

func TestConfigStructFields(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	// Test that all assist related fields are properly loaded
	assert.IsType(t, "", config.AssistRegistry)
	assert.IsType(t, "", config.AssistModelTagApple)
	assert.IsType(t, "", config.AssistModelTagIntel)

	// Test that the values are correct
	assert.Equal(t, "krknctl-assist", config.AssistRegistry)
	assert.Equal(t, "apple-silicon", config.AssistModelTagApple)
	assert.Equal(t, "intel", config.AssistModelTagIntel)

	// Test that other existing fields are still working
	assert.Equal(t, "quay.io", config.QuayHost)
	assert.Equal(t, "krkn-chaos", config.QuayOrg)
	assert.Equal(t, "krkn-hub", config.QuayScenarioRegistry)
	assert.Equal(t, "krkn", config.QuayBaseImageRegistry)
	assert.Equal(t, "latest", config.QuayBaseImageTag)
}

func TestConfigJSONStructure(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	// Test integer fields
	assert.IsType(t, 0, config.TableFieldMaxLength)
	assert.IsType(t, 0, config.TableMaxStepScenarioLength)
	assert.Greater(t, config.TableFieldMaxLength, 0)
	assert.Greater(t, config.TableMaxStepScenarioLength, 0)

	// Test string fields that should not be empty
	requiredStringFields := []string{
		config.Version,
		config.QuayHost,
		config.QuayOrg,
		config.QuayScenarioRegistry,
		config.QuayBaseImageRegistry,
		config.QuayBaseImageTag,
		config.QuayRepositoryAPI,
		config.CustomDomainHost,
		config.PrivateRegistryBaseImageTag,
		config.ContainerPrefix,
		config.KubeconfigPrefix,
		config.PodmanDarwinSocketTemplate,
		config.PodmanLinuxSocketTemplate,
		config.PodmanSocketRoot,
		config.PodmanRunningState,
		config.DockerSocketRoot,
		config.DockerRunningState,
		config.DefaultContainerPlatform,
		config.AssistRegistry,
		config.AssistModelTagApple,
	}

	for _, field := range requiredStringFields {
		assert.NotEmpty(t, field, "Required string field should not be empty")
	}
}

func TestConfigEnvironmentVariableFields(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	// Test that environment variable field names are correct
	envFields := map[string]string{
		config.EnvPrivateRegistry:          "KRKNCTL_PRIVATE_REGISTRY",
		config.EnvPrivateRegistryUsername:  "KRKNCTL_PRIVATE_REGISTRY_USERNAME",
		config.EnvPrivateRegistryPassword:  "KRKNCTL_PRIVATE_REGISTRY_PASSWORD",
		config.EnvPrivateRegistrySkipTLS:   "KRKNCTL_PRIVATE_REGISTRY_SKIP_TLS",
		config.EnvPrivateRegistryToken:     "KRKNCTL_PRIVATE_REGISTRY_TOKEN",
		config.EnvPrivateRegistryScenarios: "KRKNCTL_PRIVATE_REGISTRY_SCENARIOS",
		config.EnvPrivateRegistryInsecure:  "KRKNCTL_PRIVATE_REGISTRY_INSECURE",
	}

	for actual, expected := range envFields {
		assert.Equal(t, expected, actual, "Environment variable name should match expected value")
	}
}

func TestConfigGithubFields(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	// Test GitHub related URLs
	assert.Contains(t, config.GithubLatestRelease, "github.com")
	assert.Contains(t, config.GithubLatestRelease, "releases/latest")
	assert.Contains(t, config.GithubReleaseAPI, "api.github.com")

	// Test that URLs are properly formatted
	assert.True(t, strings.HasPrefix(config.GithubLatestRelease, "https://"))
	assert.True(t, strings.HasPrefix(config.GithubReleaseAPI, "https://"))

	// GithubLatestReleaseAPI is optional/deprecated - only test if present
	if config.GithubLatestReleaseAPI != "" {
		assert.Contains(t, config.GithubLatestReleaseAPI, "api.github.com")
		assert.True(t, strings.HasPrefix(config.GithubLatestReleaseAPI, "https://"))
	}
}

func TestConfigLabelFields(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	// Test that label fields contain expected prefixes
	labelFields := []string{
		config.LabelTitle,
		config.LabelDescription,
		config.LabelInputFields,
		config.LabelTitleGlobal,
		config.LabelDescriptionGlobal,
		config.LabelInputFieldsGlobal,
	}

	for _, field := range labelFields {
		assert.Contains(t, field, "krknctl", "Label field should contain krknctl prefix")
	}

	// Test regex fields contain proper regex patterns
	regexFields := []string{
		config.LabelTitleRegex,
		config.LabelDescriptionRegex,
		config.LabelInputFieldsRegex,
		config.LabelTitleRegexGlobal,
		config.LabelDescriptionRegexGlobal,
		config.LabelInputFieldsRegexGlobal,
	}

	for _, field := range regexFields {
		assert.Contains(t, field, "LABEL", "Regex field should contain LABEL")
		assert.Contains(t, field, "krknctl", "Regex field should contain krknctl")
	}
}

// Test error handling for invalid JSON (this would require mocking the embedded file)
func TestConfigTypes(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	// Verify field types are correct
	assert.IsType(t, "", config.AssistRegistry)
	assert.IsType(t, "", config.AssistModelTagApple)
	assert.IsType(t, "", config.Version)
	assert.IsType(t, "", config.QuayHost)
	assert.IsType(t, "", config.QuayOrg)
	assert.IsType(t, 0, config.TableFieldMaxLength)
	assert.IsType(t, 0, config.TableMaxStepScenarioLength)
}

// Test that the config loading preserves all existing functionality
func TestConfigBackwardCompatibility(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	// Test that all existing URI methods still work
	quayURI, err := config.GetQuayImageURI()
	assert.NoError(t, err)
	assert.NotEmpty(t, quayURI)

	customURI, err := config.GetCustomDomainImageURI()
	assert.NoError(t, err)
	assert.NotEmpty(t, customURI)

	scenarioAPI, err := config.GetQuayScenarioRepositoryAPIURI()
	assert.NoError(t, err)
	assert.NotEmpty(t, scenarioAPI)

	baseImageAPI, err := config.GetQuayBaseImageRepositoryAPIURI()
	assert.NoError(t, err)
	assert.NotEmpty(t, baseImageAPI)

	// Test the assist image URI method
	assistURI, err := config.GetAssistImageURI()
	assert.NoError(t, err)
	assert.NotEmpty(t, assistURI)
}

func TestGetAssistImageURIWithRegistry(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	// Test with custom registry and custom repository
	uri, err := config.GetAssistImageURIWithRegistry("my-registry.example.com", "custom-assist")
	assert.NoError(t, err)
	assert.NotEmpty(t, uri)
	assert.Contains(t, uri, "my-registry.example.com")
	assert.Contains(t, uri, "custom-assist")
	// Tag is platform-specific (either AssistModelTagApple or AssistModelTagIntel)
	assert.True(t, strings.HasSuffix(uri, ":"+config.AssistModelTagApple) ||
		strings.HasSuffix(uri, ":"+config.AssistModelTagIntel))

	// Test with custom registry but default repository
	uri, err = config.GetAssistImageURIWithRegistry("my-registry.example.com", "")
	assert.NoError(t, err)
	assert.NotEmpty(t, uri)
	assert.Contains(t, uri, "my-registry.example.com")
	assert.Contains(t, uri, config.AssistRegistry)

	// Test with empty registry (should fall back to public registry)
	uri, err = config.GetAssistImageURIWithRegistry("", "")
	assert.NoError(t, err)
	assert.NotEmpty(t, uri)
	publicURI, _ := config.GetAssistImageURI()
	assert.Equal(t, publicURI, uri)
}

func TestConfigBooleanLabelRegex(t *testing.T) {
	config, err := LoadConfig()
	assert.NoError(t, err)

	// Test that boolean label NAME fields are loaded
	assert.NotEmpty(t, config.LabelIsAScenario, "LabelIsAScenario should not be empty")
	assert.NotEmpty(t, config.LabelHasRollback, "LabelHasRollback should not be empty")
	assert.Equal(t, "krknctl.is_a_scenario=", config.LabelIsAScenario)
	assert.Equal(t, "krknctl.has_rollback=", config.LabelHasRollback)

	// Test that boolean label REGEX fields are loaded
	assert.NotEmpty(t, config.LabelIsAScenarioRegex, "LabelIsAScenarioRegex should not be empty")
	assert.NotEmpty(t, config.LabelHasRollbackRegex, "LabelHasRollbackRegex should not be empty")

	// Test that regex contains the expected pattern with spaces support
	assert.Contains(t, config.LabelIsAScenarioRegex, "\\s*=\\s*", "Regex should support spaces around =")
	assert.Contains(t, config.LabelHasRollbackRegex, "\\s*=\\s*", "Regex should support spaces around =")

	// Test that regex can be compiled
	_, err = regexp.Compile(config.LabelIsAScenarioRegex)
	assert.NoError(t, err, "LabelIsAScenarioRegex should be valid regex")

	_, err = regexp.Compile(config.LabelHasRollbackRegex)
	assert.NoError(t, err, "LabelHasRollbackRegex should be valid regex")

	// Debug output
	t.Logf("LabelIsAScenario: %q", config.LabelIsAScenario)
	t.Logf("LabelHasRollback: %q", config.LabelHasRollback)
	t.Logf("LabelIsAScenarioRegex: %q", config.LabelIsAScenarioRegex)
	t.Logf("LabelHasRollbackRegex: %q", config.LabelHasRollbackRegex)
}
